### ISSUE TITLE
Problem with password handling refactor

### ISSUE THREAD

**Issue by edlmo** [dyne/tomb#125]
Using Tomb for about 4-5 months here.
After pull the repository today, Tomb is no longer able to use the secret key to mount the encrypted file I have always used.
I've  followed the problem to the commit [5158c38](https://github.com/dyne/Tomb/commit/5158c380fefa46396ce3f2ec6ca6b994384de7d2#diff-d41d8cd98f00b204e9800998ecf8427e), but didn't look further.

Here is the output from my command line (real paths has been changed):

```
$ sudo ./tomb exhume /path/image.jpg -k - | sudo ./tomb open -f -k - /path/file.tomb
tomb  .  Commanded to open tomb /path/file.tomb
tomb  .  Trying to exhume a key out of image /path/image.jpg
tomb  >  Waiting for the key to be piped from stdin... tomb (*) - succesfully decoded.
ok
tomb [W] Key data found with missing headers, attempting recovery.
tomb  .  Mountpoint not specified, using default: /media/file.tomb
tomb (*) Opening file.tomb on /media/file.tomb
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha1"
tomb  .  A password is required to use key stdin.tmp.key
tomb  .  Valid key file found: /dev/shm/tomb.load_key_stdin.4093.cYHVH9f/stdin.tmp.key
tomb  .  Password OK.
No key available with this passphrase.
tomb  .  Removing key temporarily stored from stdin
tomb [E] Failure mounting the encrypted file.
```

**Comment by genius-Loci** [comment]
hi, my problem is:
tomb [W] Attempting key recovery.
tomb  .  Password OK.
tomb [E] Failure mounting the encrypted file.

**Comment by Narrat** [comment]
If using ZSH 5.3 see the README.md or #232

**Comment by genius-Loci** [comment]
Problem solved, Thank you.
