### ISSUE TITLE
problem with hidden files (starting with .)

### ISSUE THREAD

**Issue by ajs124** [dyne/Tomb#147]
So I was testing tomb (1.5.3) and named my tomb ".foo.tomb".
When I open said tomb, it spits out a tune2fs error. By executing the script with set -x I found out that the $tombname variable is empty, which is most likely due to the regex in [this line](https://github.com/dyne/Tomb/blob/master/tomb#L338).
This might cause other problems, too.

**Comment by Pawamoy** [comment]
Still encounter this issue in Tomb 2.4:

```bash
pawamoy@blldlc ~ $ sudo tomb -D open .local_tomb -k .local_key
tomb [D] Identified caller: pawamoy (1000:1000)
tomb [D] Updating HOME to match user's: /home/pawamoy (was /root)
tomb [D] Tomb command: open .local_tomb
tomb [D] Caller: uid[1000], gid[1000], tty[/dev/pts/0].
tomb [D] Temporary directory: /tmp/zsh
tomb  .  Commanded to open tomb .local_tomb
tomb [D] is_valid_tomb .local_tomb
tomb [D] tomb file is readable
tomb [D] tomb file is a regular file
tomb [D] tomb file is not empty
tomb [E] Tomb won't work without a TOMBNAME.
```

**Comment by jaromil** [comment]
ACK. The transformation made by ` ${${TOMBFILE// /_}%.*}` is meant to remove the extension .tomb, but if the tombfile starts with a dot and has no extension then it just removes all its name. I'm open to suggestions on how to solve this, first thing that comes in mind is adding an exception like "starting with a dot and has only one dot in filename"...

**Comment by Pawamoy** [comment]
Yeah, seems good to me, I would have suggest the same thing. Or... we could add a positional parameter to `open` command to specify the tomb name.
