### ISSUE TITLE
autogrow

### ISSUE THREAD

**Issue by hellekin** [dyne/Tomb#148]
Wouldn't it be nice to have a hook that tells the tomb to automatically grow when it reaches some determined fill, such as 90%? `autogrow` would make it easier to use `tomb` as a drop-in replacement for `eCryptFS` or `EncFS` for home directory encryption.

Of course it would require taking into account the available space on the container, and a configurable upper limit to growth--one reason I see for that is the will to keep the tomb portable, e.g. one could wish to limit it to the size of an SD card.

**Comment by jaromil** [comment]
closing this, as it should be implemented as hook.
