### ISSUE TITLE
Weblate as a Translation Framework

### ISSUE THREAD

**Issue by JoelMon** [dyne/Tomb#158]
# Translating Software

A discussion that appeared in issue #157.
- [Pootle](http://pootle.translatehouse.org)
- [Weblate.org](http://www.weblate.org)
## Weblate

Weblate is Developed by [Michal Čihař](https://cihar.com/) from Prague, Czech Republic. He also contributes to Debian, phpMyAdmin, and other projects.

Weblate is like Pootle in that the translating framework runs on a web-server. One major area where Weblate differs from Pootle is in regards to integration with GitHub. With Weblate you point towards the repository where you keep your internalization files Weblate then uses said repository to provide a front end to translators. It's also pretty cool how Weblate can also work with branches. For example, it can pull/push to all open branches it is configured to pull/push to. Say you have a Tomb 2.0 branch going for a few months, translators can start working on that translation as it's being developed.

Weblate supports characters based languages and languages that are written right to left.

Weblate is in written Python, it takes advantage of the Python [translate toolkit](http://toolkit.translatehouse.org/) (parses many kinds of translation [formats](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/index.html)) so Weblate has built in support for translation formats that the Python translate toolkit supports (I'm assuming).

When downloading Weblate it's nice to note that the master upstream on Github is always stable.

A feature that is nice for contributors is that when a person contributes with Weblate, the commits are credited using the translator's Github account.
### Future features in the works:

Not sure if this has been implemented yet, I don't know the date where I heard about this. It may have been already rolled out.
- Translation voting
- Android support stings support
### Hosting

There is also the option to have weblate.org host your project.
#### Translation workflow

All translated repositories are available at git.weblate.org with similar naming as on website - hello/master translation would be published as git://git.weblate.org/hello-master.git.

To enable automated workflow on GitHub, you need to enable Weblate service hook in settings with hosted.weblate.org as URL. If you want Weblate to automatically push changes as well, add Weblate user to contributors and let us know you want to use this option.

To enable automated workflow on Bitbucket, you need to add POST hook to http://hosted.weblate.org/hooks/bitbucket/ URL. If you want Weblate to automatically push changes as well, give Weblate user write permission to your repository and let us know you want to use this option. [source](https://weblate.org/en/hosting/)
#### Hosted projects

List of hosted projects: [List](https://hosted.weblate.org/)
### Examples of Weblate Being Used
- [PHPMyAdmin](https://hosted.weblate.org/projects/phpmyadmin/)
- [Debian Handbook](https://hosted.weblate.org/projects/debian-handbook/)
### Demo

You can try a demo of Weblate [here](https://demo.weblate.org/).

**Comment by jaromil** [comment]
We ended up running translations on poeditor, account maintained by @gdrooid.
