### ISSUE TITLE
Suggestion: display some line before trying to go superuser

### ISSUE THREAD

**Issue by fsLeg** [dyne/Tomb#171]
It's kinda misleading when Tomb suddenly asks for a password in a terminal with no warning. We know that password in a terminal is asked by sudo, while a password for a key is asked by pinentry, which in most cases will be graphical. But users don't know that, so it might be confusing for them at first.

There was an issue about password requests being more homogenic. I ask to somehow label what exactly password is asked, for sudo or a key. Something like: "Trying to go superuser...", then sudo prompt.

**Comment by jaromil** [comment]
Just committed a fix introducing a new translatable string used in the sudo prompt, to be inserted manually (ping @gdrooid ) the string is:

`"[sudo] Enter password for user ::1 user:: to gain superuser privileges"`

**Comment by gdrooid** [comment]
I'm working on it ;)

**Comment by jaromil** [comment]
blazing fast! thanks :^)

**Comment by gdrooid** [comment]
Everything is up-to-dato on POEditor now, I'll push changes to git soon.

**Comment by jaromil** [comment]
cheers!
