### ISSUE TITLE
Tomb trending in /r/commandline

### ISSUE THREAD

**Issue by JoelMon** [dyne/Tomb#183]
Tomb is currently trending in [/r/commandline](https://www.reddit.com/r/commandline/).

**Comment by jaromil** [comment]
Nice. was also in /r/netsec 6 months ago and some criticism was useful for the 2.0 roadmap.
Lets see what comes out of this, there is always something to learn.
Thanks for signaling it.

**Comment by JoelMon** [comment]
I'll go ahead and link to the comment sections of posts made recently.

[/r/commandline](https://www.reddit.com/r/commandline/comments/2rb45p/tomba_shell_script_to_manage_luks_volumes_easily/)
[/r/linux](https://www.reddit.com/r/linux/comments/2rb1zj/tomba_shell_script_to_manage_luks_volumes_easily/)
