### ISSUE TITLE
Small mistake in a message string

### ISSUE THREAD

**Issue by Narrat** [dyne/Tomb#184]
Hi

One small thing for that I didn't want to open a PR
https://github.com/dyne/Tomb/blob/master/tomb#L1508
it and dig should be swapped

**Comment by jaromil** [comment]
better have gdrooid look at this, since he knows better how and where to correct it without messing up translations.

**Comment by gdrooid** [comment]
Fixed tomb itself and the translation files in bd7300aa3ecb667f0e5b3ee252b42a3fedcb933c. Thank you @Narrat!
