### ISSUE TITLE
GTK2_RC_FILES is set to empty when custom skull dialog not installed

### ISSUE THREAD

**Issue by alexwh** [dyne/Tomb#185]
I export GTK2_RC_FILES in my profile at login in order to get GTK2 themes working properly on my system - on [line 395](https://github.com/dyne/Tomb/blob/9bcf530c0f77194a20a9add068d79b3f46931e6e/tomb#L395), GTK2_RC_FILES is set for pinentry even if $gtkrc is empty. This clears my globally exported settings and makes the pinentry dialog look ugly, instead of using the proper themes:

![before](http://i.imgur.com/n5MlnXF.png)

![after](http://i.imgur.com/CEraMwz.png)

**Comment by jaromil** [comment]
thanks for noticing
