### ISSUE TITLE
tomb unable to open inside docker with tomb script (opens manually) 

### ISSUE THREAD

**Issue by guruvan** [dyne/Tomb#188]
I've had a read through issue #154 which gave the necessary commands to open my tomb files manually inside my docker containers, but I'm not able to open via tomb script. 

Running tomb as root inside the docker container, with the latest (pulled today) git master, I'm seeing
```
pinentry-curses: no LC_CTYPE known - assuming UTF-8
```
(ubuntu - phusion/baseimage) 

Prior version was providing <code>"No key available with this passphrase" </code> after saying <code>"Password OK" </code> 
If run as non-priv user, I see <code>unable to create here document</code> error

this allowed me to open the file:
```
lo=$(losetup -f)
 losetup -f secret.tomb
 pass=$(gpg -d secret.key)
 echo -ne "$pass" | cryptsetup --key-file - luksOpen $lo secret
 mount /dev/mapper/secret $HOME/secret-contents
```
The container is run with the following (and this worked with the manual code above):
```
docker run -it -rm \
 ---privileged  \
 -v /lib/modules:/lib/modules \
 -v /home/someone:/home/someone \
 --device /dev/loop0:/dev/loop0 \
 --device /dev/fuse:/dev/fuse \
myphusion/baseimage /bin/bash
```
The container image has gnupg2 inside. While the issue seems to center around pinentry-curses, gpg works fine inside - pinentry-curses is used to enter passphrase, and gpg key is usable. I've tried both with, and without gpg-agent daemon running. 

Any thoughts how to get this working reliably? Anything I can provide to help diagnose?

**Comment by jaromil** [comment]
hi Rob,

I can't understand well from your report: when using the current master/HEAD in git you get
```
pinentry-curses: no LC_CTYPE known - assuming UTF-8
```
as an error, and then? does it quits right after with no other error message?

**Comment by guruvan** [comment]
There's a little form tomb that follows:

```
pinentry-curses: no LC_CTYPE known - assuming UTF-8
tomb [W] Pinentry error: syntax
tomb [W] User aborted password dialog.
tomb [E] No valid password supplied.
```

**Comment by jaromil** [comment]
ACK! just to be sure, can you add a `-D` flag for debug output? it might be that there is no debug.

BTW your report makes me also notice that the README snippet for manual tomb opening is wrong and yours is correct. I also notice that both (yours and the one in the README) only work from ZSh and not in Bash (go figure... I'll figure...).

**Comment by jaromil** [comment]
Can you please try adding a control to see if $LANG is empty before calling pinentry? it might be that the docker container hasn't set it. On line 366 (before the $DISPLAY check) add:
```
LANG=${LANG:-en_US.UTF-8}
```
I wonder if this should be the default, or if C also would work. To help me figure then try changing that in:
```
LANG=${LANG:-C}
```

**Comment by jaromil** [comment]
Oh neverming, I can take it from that! could reproduce the error using `unset LANG` so my guess is right: your docker is not setting LANG (soon enough?). However nice to handle also this case in tomb.
I'll test the best fix.

Eventually will open another issue about the manual opening...

**Comment by guruvan** [comment]
Actually @jaromil this is all running from bash as my working shell. Didn't notice the above manual method in README (didn't look!) - got from issue #154 Perhaps I should use zsh as a login shell and try that way as well and we'll see if there's a different result. I'll get some -D output.

$LANG is not set in the container

And you're FAST! :) Thanks!

```

**Comment by jaromil** [comment]
cheers! (love mazacoin <3)

**Comment by guruvan** [comment]
<3

**Comment by guruvan** [comment]
Finally had a chance to test this fix :) works perfectly as root. pinentry-curses dialog doesn't come up as non priv user - but this is working for me! :) Thank you

(you should send a mazacoin address!) guruvan at maza club

**Comment by jaromil** [comment]
go maza go! MTaK8nWWvsCEJpcvxVyQigZDho51KM6Q1s

yes the drop of privilege on pinentry is not happening anymore since last sudo refactoring (2.0) to use less code and facilitate use from normal su
