### ISSUE TITLE
Wrong last user in tomb list

### ISSUE THREAD

**Issue by arthaud** [dyne/Tomb#198]
Hi,

When I'm using `tomb list`, the last visited user is wrong.

It's because you are looking for `:$uid:` in */etc/passwd*. Actually, my */etc/passwd* looks like:
```
maxima:x:1000:100:maxima:/home/maxima:/bin/zsh
skype:x:1001:1000::/home/skype:/bin/false
```

and therefore, looking for `:1000:`, user *skype* is found instead of me.

This happens here: https://github.com/dyne/Tomb/blob/master/tomb#L1821-L1824 and there: https://github.com/dyne/Tomb/blob/master/tomb#L1986-L1989

You could probably use ``getent passwd $uid``

**Comment by hellekin** [comment]
Right, is `getent` available for *BSD?

Otherwise using awk could work as well:

```
tombuser=$(awk -F: '/^[^:]+:x:'$tombuid':/ {print $1}' /etc/passwd)
```

Using `getent`:

```
tombuser=$(getent passwd $tombuid | awk -F: '{print $1}')
```

**Comment by arthaud** [comment]
I don't know. Your example using awk seems good.

**Comment by hellekin** [comment]
Minimal patch, replace:

```
[[ "$ee" =~ ":${tombuid}:" ]] && {
```

with

```
[[ "$ee" =~ ":x:${tombuid}:" ]] && {
```

(Both my proposals assume use of shadow passwords.)

**Comment by boyska** [comment]
On Tue, Apr 14, 2015 at 01:40:28PM -0700, hellekin wrote:
>Otherwise using awk could work as well:
>
>```
>tombuser=$(awk -F: '/^[^:]+:x:'$tombuid':/ {print $1}' /etc/passwd)

I'd prefer

```sh
awk -F: '$4 == '$tombuid' { print $1 }'
```

>```
>tombuser=$(getent passwd $tombuid | awk -F: '{print $1}')
>```

this is maybe clearer with `cut`:
```sh
getent passwd $tombuid | cut -d: -f1
```

**Comment by hellekin** [comment]
Fair enough.

**Comment by hellekin** [comment]
@jaromil I put the fix into a branch.  Please ack and close the issue.

**Comment by jaromil** [comment]
ACK. Two observations:

1) Tomb is not compabible with BSD. If we aim for that, we need some BSD expert to join our team first, then we can target use of tcplay instead of cryptsetup (hence modularize that part of the code) and then finalize. Until we take this route there is no concern against using `getent`.

2) ZSh has native support for simple string-token operations, which is preferable than spawning extra processes. In this case a fully native formula would be:
```bash
getent passwd $tombuid | sysread tombuser
tombuser=${tombuser[(ws@:@)1]}
```

**Comment by boyska** [comment]
point 3 is conceptually wrong. getent does not just read `/etc/passwd`, it
> get entries from Name Service Switch libraries

so if you want to reimplement it (but why?) you should actually reimplement a parser for `/etc/nsswitch.conf`; good luck with that.

**Comment by jaromil** [comment]
Eventually, in 3) I mention we may parse `/etc/passwd` natively, not cover all `getent` functionalities.

**Comment by boyska** [comment]
So you might not found the user. Not every user is in `/etc/passwd`.

**Comment by jaromil** [comment]
You are right. Lets resort to solution 2).
Wait for hellekin to respond so we don't waste his branch, he is on another timezone.
