### ISSUE TITLE
Disable history

### ISSUE THREAD

**Issue by arthaud** [dyne/Tomb#201]
Hi,

I just figured out that we might want to hide some commands so that they don't go in the history file.
For instance, using ``tomb open Data.tomb -k Images/Summer2015/GreatPicture.jpg`` we don't want to put the path to the steganographic key in the history file.

I didn't find any way to do that, except returning an error. We may just add a comment somewhere to ask people to use the zsh HISTIGNORESPACE feature.

Best.

**Comment by jaromil** [comment]
It is done by: `alias tomb=' tomb'` and the env HISTIGNORESPACE=1
