### ISSUE TITLE
Account expired on poeditor translation webservice

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#203]
The third-party service we were using has closed my account because of not logging into it often enough.

@gdrooid would you like to setup a new account that you can administer directly?

I'm sure we do not have time to explore another service or setup our own, but I welcome anyone with problems using poeditor (referring to a past thread) to come up with a working solution.
Else lets stay there.

**Comment by gdrooid** [comment]
I'll wait until Saturday, so people can read this and comment.

**Comment by Narrat** [comment]
How to submit updates for .po files?
I want to improve de.po and it's stated
>Translations are also needed: they can be contributed via the
PO Editor web interface or simply sending us the .po file.

So can I open a PR?

On another note. I have a question about a few things:
 * MB vs MiB; What is it? https://github.com/dyne/Tomb/blob/master/extras/po/tomb.pot#L522 https://github.com/dyne/Tomb/blob/master/extras/po/tomb.pot#L158 (in case of dig. in general MB is used and MiB just once. Didn't check with the script if there is a difference)
 * Handling of sub-commands; For example in error messages: https://github.com/dyne/Tomb/blob/master/extras/po/tomb.pot#L878 vs https://github.com/dyne/Tomb/blob/master/extras/po/tomb.pot#L650 Should there be ''? (In the de translation they were set)
 * https://github.com/dyne/Tomb/blob/master/extras/po/tomb.pot#L1134 Page not found
 * in General should the URLS be changed to use https as it's possible?

**Comment by jaromil** [comment]
open a PR on github is the best way right now.

those who do not like to make an account on github can mail it to me directly

I just received corrections to the spanish translation via email....

**Comment by gdrooid** [comment]
I'm sorry that it took so long, but I've already set up a project on POEditor. Here's the new url: https://poeditor.com/join/project/b276xMGAmB

**Comment by jaromil** [comment]
thanks @gdrooid and no worries, we all have plenty of things going on in our lives.
Cheers for keeping up your love for tomb :^)

**Comment by mgian** [comment]
What about [Weblate](https://weblate.org/it/) ?
