### ISSUE TITLE
Tomb only works with .tomb extension now?

### ISSUE THREAD

**Issue by FryDay** [dyne/Tomb#204]
If I have my tomb named whatever.tomb, it works great. I used to be able to have my tomb named whatever I want. Now I get this:

tomb open things.something -k things.something.key 
tomb  .  Commanded to open tomb things.something
tomb  .  Valid tomb file found: ./things.tomb
tomb [W] things.tomb is not a valid tomb file
tomb [E] Operation aborted.

This is on Ubuntu 14.04, if it matters.

**Comment by Narrat** [comment]
See https://github.com/dyne/Tomb/issues/180

**Comment by FryDay** [comment]
Good call. I was using the latest release, not the latest dev version.

**Comment by jaromil** [comment]
I think latest dev version is safe to use right now, yesterday I run regression tests and its approaching to be tagged stable.
