### ISSUE TITLE
Debate Tomb on Slashdot

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#212]
Here a post on the most popular geek forum debating our software Tomb

http://it.slashdot.org/story/15/07/25/0043206/tomb-a-successor-to-truecrypt-for-linux-geeks

for those liking to participate and offer insights.

I'm especially interested in everyone's opinion about the relation between simplicity and security.

**Comment by Narrat** [comment]
If it ever comes to that discussion. Currently they're still debating about the topic

**Comment by jaromil** [comment]
I evince some good points

1- cross-platform support is important. Let's prioritize this issue in librecrypt https://github.com/t-d-k/LibreCrypt/issues/9 which is also rather easy to get. If you can, please contribute to librecrypt!

2- people DO care about simplicity and interoperability with standards. Truecrypt is considered a reliable standard by many. Perhaps we can optionally support librecrypt's cross-platform exec in place of the system-wide cryptsetup, but then i think isn't worthed as most win/osx users don't use a terminal

3- best thing possible is to have tombs that can be opened with other cross-platform programs, not to have tomb working cross-platform IMHO, since its usage is willingly limited to term-loving geeks or at least people who aren't afraid to call a script with its name


At last, I did not read many concerns about bit-rot which is surprising, some good point about headers I've responded to and i'm more and more convinced we do want to have the header backupped into the key, as this will make tomb more resistant to data corruption (see issue #67 at bottom). First step for this is to include a test suite dedicated to file corruption situations: like changing bytes in a tomb and see if it opens, study how such cases can be recovered, remove/replace headers and such. Perhaps even experiment with error-correction algorithms on top of the gnupg key material.
