### ISSUE TITLE
Nested tombs behaviour

### ISSUE THREAD

**Issue by StrangeTcy** [dyne/Tomb#217]
Disclaimer: I think that the use case here is a weird and improbable one, so analysing it is not a priority.

Let's say I create a tomb called outer.tomb, open it and then in it I create a smaller tomb called inner.tomb.
Then I open the inner tomb. And then try to close the outer one. 
At the moment, I'm unable to do that, since inner tomb is mounted and busy. And I think that since I opened the inner tomb manually I should also close it manually. 
But is it possible to enable tomb to detect such nested structures and upon closing the outer tomb close all its' inner ones?

**Comment by jaromil** [comment]
Of course is possible, but it has to be written in code. I doubt it would look good. Perhaps it should be scripted into an exec-hook and not part of tomb's code.
