### ISSUE TITLE
fuser vs lsof (slam fails, can't reproduce yet)

### ISSUE THREAD

**Issue by fleanegan** [dyne/Tomb#220]
I am running arch linux with the AUR tomb-git + tomb-kdf-git package.
Everytime I enter "slam all" or "slam all -f" while having a program accessing a file in my active tomb, I get "target is busy" and try fuser(1).

I hope, that this is the right place for this issue.
Good evening, gentlemen

**Comment by parazyd** [comment]
Post the output of `tomb slam all -D` and fuser output when this happens.

**Comment by jaromil** [comment]
Good to investigate this and yes it may be fixed along with the whitespace commit. Please @fleanegan when you can let us know how this behaves in latest 2.2 release.

**Comment by Narrat** [comment]
It's still reproduceable with latest master snapshot.
Arch, tomb-git build based on a08cb6e, open terminal in mount location.

>$ LANG=C tomb slam all -D
tomb [D] Identified caller: omnius (1000:100)
tomb [D] Tomb command: slam all
tomb [D] Caller: uid[1000], gid[100], tty[/dev/pts/5].
tomb [D] Temporary directory: /tmp/zsh
tomb [D] Name: [Transfer]
tomb [D] Mount: /run/media/omnius/Transfer
tomb [D] Mapper: tomb.Transfer.1452008442.loop0
tomb (*) Slamming tomb [Transfer] mounted on /run/media/omnius/Transfer
tomb  .  Kill all processes busy inside the tomb.
tomb [D] Performing umount of /run/media/omnius/Transfer
umount: /run/media/omnius/Transfer: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
tomb [E] Tomb is busy, cannot umount!

fuser isn't that informative

>$ LANG=C fuser -v /run/media/omnius/Transfer/
                     USER        PID ACCESS COMMAND
/run/media/omnius/Transfer:
                     root     kernel mount /run/media/omnius/Transfer

**Comment by Narrat** [comment]
lsof is working

> $ lsof +D /run/media/omnius/Transfer
lsof: WARNING: can't opendir(/run/media/omnius/Transfer/lost+found): Permission denied
COMMAND   PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
termite 15097 omnius  cwd    DIR  254,0     4096    2 /run/media/omnius/Transfer
zsh     15100 omnius  cwd    DIR  254,0     4096    2 /run/media/omnius/Transfer

**Comment by jaromil** [comment]
is `/run/media` a symlink? the new directory location "standard" needed already a special handling in our code...

**Comment by Narrat** [comment]
No. the Media folder will be created, but it's not a symlink.
The stuff is running on a tmpfs.

**Comment by jaromil** [comment]
that's my wild guess then: tmpfs doesn't implements the api calls required by fuser.

should we revert to lsof? change made in commit e482f753daaf881d16bb05cd248d970d7498aad8

**Comment by Narrat** [comment]
It seems to be something special how it is used for /run.
Other tmpfs based mounts, like /tmp work with fuser.

I would like to know what's happening first, before commenting if something should be reverted

**Comment by parazyd** [comment]
Narrat, try installing udisks on Arch. It's in the "extra" repo.

**Comment by Narrat** [comment]
What for? Just to get /media back? Could be done by hand.
In my opinion not a good reason at all.
Despite the fact that udisks2 replaced udisks (Yeah, I know about those blog posts, where they lament about it)

**Comment by Narrat** [comment]
Time has gone by and I'm not wiser :D
For some it seems to work with fuser and for some not. And reintroducing the lsof based handling is kinda ugly.

**Comment by jaromil** [comment]
Yes, the fuser code is much better looking and you are right we shouldn't touch it without knowing exactly why this issue occurs.

As you find some time, please try to reproduce this bug.
We need to find out what is this "*something special how it is used for /run.*"

**Comment by Narrat** [comment]
I still cannot figure out, why fuser causes those problems (maybe some kind of permission problem).

Looking again at a solution with lsof, without reintroducing the previous mess.
Any specific reason why lsof cannot be used in the way fuser is?
The manual mentions as an example
```
$ kill -HUP `lsof -t /u/abe/bar`
```
Where the signal could be set from a variable like it is done with the for loop and the kill option of fuser?

**Comment by jaromil** [comment]
It's a good guess, but just a guess until we find a way to replicate the bug or at least trigger it with a stress-testing unit.

**Comment by Narrat** [comment]
Jeah. 
Therefore I want to set up some VMs in the next few days, looking at distributions where it seems to be working.

**Comment by Narrat** [comment]
Neither with Debian, Fedory, nor with Devuan I am getting a useful result with fuser, when checking the /run directories (only one is the one from the kernel with the mount info), whereas lsof reports back

**Comment by jaromil** [comment]
Thanks for following up and testing. We shall switch to lsof then. You are very welcome to make a pull-request.
