### ISSUE TITLE
Unrecognized option --sudo-pwd for subcommand lock

### ISSUE THREAD

**Issue by parazyd** [dyne/Tomb#221]
While writing a GUI wrapper, I must use an external input for a sudo password. `man tomb` told me about `--sudo-pwd <string>`. However, when using it while locking a new tomb, I get an error saying `tomb [E] Unrecognized option --sudo-pwd for subcommand lock`.
Is it not implemented in the lock command, or am I doing something wrong?

**Comment by jaromil** [comment]
docs were imprecise, option was removed, sudo has different ways to solve that

cleaned up from manpage here 97399f6b918ef6f99dfe6b22bdfcd0cd346738d6

and we did solve this in person now for your gui! looking forward to is :^)
