### ISSUE TITLE
Username change breaks sudo

### ISSUE THREAD

**Issue by robertmx** [dyne/Tomb#223]
In tomb 2.2, the username change breaks the recommended (by the man page) sudo access to the script. Adding

robert ALL=NOPASSWD: /home/robert/tomb

to /etc/sudoers and then executing the tomb script from my home directory via

sudo ./tomb -D lock test.tomb -k test.tomb.key

(for testing and coding purposes only - I know about the security implications) results in the script prompting for the sudo password. This should not be necessary because the script already is running at elevated privileges. I would like to give normal users the ability to use tomb, but no way I am going to permit mounts etc. The culprit is the forced user name change on line 213. The following patch restores the expected behaviour

[tomb.patch.txt](https://github.com/dyne/Tomb/files/94506/tomb.patch.txt)

I think giving users privileged access to the tomb script is acceptable and should have limited impact on security if the script itself is not vulnerable. Giving them all the privileges required by tomb individually would effectively elevate every potential user of tomb to the privilege level of root. I did not review the security implications of the above patch. I merely consider it a patch restore the expected behaviour as described in the man pages.

**Comment by robertmx** [comment]
Cleaned up the patch - I forgot one comment from tracing through the code.

[tomb.patch.txt](https://github.com/dyne/Tomb/files/94522/tomb.patch.txt)

**Comment by jaromil** [comment]
thanks @robertmx for the patch!
