### ISSUE TITLE
Resize issue

### ISSUE THREAD

**Issue by reiven** [dyne/Tomb#227]
Hi

I'm trying to resize a tombfile of 3000mb to 4096mb but it failed twice, same error

```
tomb  .  Generating smallown.tomb of 4096MiB
dd: error writing ‘standard output’: File too large
1096+0 records in
1095+0 records out
1149239295 bytes (1.1 GB) copied, 328.467 s, 3.5 MB/s
tomb [E] Error creating the extra resize ::1 size::, operation aborted.
```

I'm using tomb 2.1

**Comment by jaromil** [comment]
what filesystem is the tomb inside? I think it may not support 4gb files (also see dmesg)

**Comment by reiven** [comment]
You are completely right, i was sure the pend i'm using was using ext4 but i was wrong. Now its working
