### ISSUE TITLE
Error in release for 2.2

### ISSUE THREAD

**Issue by reiven** [dyne/Tomb#231]
Hi!

I've just downloaded the tar.gz for version 2.2 from Releases page (https://github.com/dyne/Tomb/releases) and the packed file still says 'typeset VERSION="2.1"' which is wrong/confusing.

**Comment by jaromil** [comment]
should not use the release page on github!! the official releases are on https://files.dyne.org

is there a way to deactivate github releases based on tags?

**Comment by Narrat** [comment]
As far as I know only by deleting the tags from the github repo and avoiding to push those later on.
Which isn't a good solution.
Couldn't it be easier to use signed tags? So downloads from dyne and github are both signed.

**Comment by jaromil** [comment]
errare humanum est, see a08cb6e0def4361ea97350d5f5b16e2f3b8bc089
