### ISSUE TITLE
tomb broke

### ISSUE THREAD

**Issue by tomw1982** [dyne/Tomb#233]
I dont now why, but after last upgrade linux I can`t open my tomb files:
$ tomb open priv.tomb -k priv.tomb.key -f -D
tomb [D] Identified caller: tomasz (1000:100)
tomb [D] Tomb command: open priv.tomb
tomb [D] Caller: uid[1000], gid[100], tty[/dev/pts/1].
tomb [D] Temporary directory: /tmp/zsh
tomb  .  Commanded to open tomb priv.tomb
tomb [D] is_valid_tomb priv.tomb
tomb  .  Valid tomb file found: priv.tomb
tomb [D] load_key argument: priv.tomb.key
tomb [D] load_key: priv.tomb.key
tomb [D] is_valid_key
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /run/media/tomasz/priv
tomb (*) Opening priv on /run/media/tomasz/priv

[sudo] Enter password for user tomasz to gain superuser privileges

tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha1"
tomb [D] dev mapper device: tomb.priv.1482264949.loop0
tomb [D] Tomb key: priv.tomb.key
tomb [D] Tomb name: priv (to be engraved)
tomb  .  A password is required to use key priv.tomb.key
tomb [D] asking password with tty=/dev/pts/1 lc-ctype=pl_PL.UTF-8
tomb [D] using pinentry-gtk2

** (pinentry-gtk-2:8454): WARNING **: it took 200 tries to grab the keyboard
tomb [D] get_lukskey
tomb [D] get_lukskey returns 0
tomb  .  Password OK.
tomb [E] Failure mounting the encrypted file.

Please help. I dont have access to many my important files.

**Comment by parazyd** [comment]
Downgrade to ZSH 5.2. In the README it's mentioned that ZSH 5.3 broke tomb.

**Comment by tomw1982** [comment]
Still not working :(

**Comment by jaromil** [comment]
As mentioned in the README, if you are in urge to recuperate your files, these simple commands will open the tomb without using the tomb script:

```
lo=$(losetup -f)
losetup -f secret.tomb
pass="$(gpg -d secret.key)"
echo -n -e "$pass" | cryptsetup --key-file - luksOpen $lo secret
mount /dev/mapper/secret /mnt
```
