### ISSUE TITLE
Update zulucrypt link in tomb homepage

### ISSUE THREAD

**Issue by reiven** [dyne/Tomb#234]
Hi!

The current zulucrypt link is poiting to google code, but the ursl says "Project has moved" and redirects to this github repo: http://mhogomchungu.github.io/zuluCrypt/

Maybe it will be a good idea to update the link

**Comment by jaromil** [comment]
do you want to make this commit yourself as well?

**Comment by reiven** [comment]
Uhm the dyne/tomb (https://www.dyne.org/software/tomb/) page is availble somewhere?

**Comment by jaromil** [comment]
ah ok is on the wp webpage. that is on another system indeed. will change or refresh the page / sync with README sometime soon... closing this issue meantime
