### ISSUE TITLE
Update included tomber version in Tomb pkg

### ISSUE THREAD

**Issue by reiven** [dyne/Tomb#235]
Actually tomber (https://github.com/reiven/tomber) is being packed in the Tomb 'extras' directory but it was not updated to latest version, and included version is incompatible from v2.2 because of the change in the '--unsafe' parameter renaming.

**Comment by jaromil** [comment]
ACK. Will update in the upcoming minor bugfix release. Thanks for looking into this and other details!

**Comment by jaromil** [comment]
would you like to file a pull request or shall I do it?

**Comment by reiven** [comment]
I'll do it, np
