### ISSUE TITLE
Setkey Unexpected error in luksClose

### ISSUE THREAD

**Issue by reiven** [dyne/Tomb#236]
Hi

Using the setkey manually is giving "Unexpected error in luksClose" but the key was changed correctly.
This is the output of the command:

> tomb  .  Commanded to reset key for tomb 4281.tomb
tomb  .  Valid tomb file found: 4281.tomb
tomb  .  Key is valid.
tomb (*) Changing lock on tomb 4281
tomb  .  Old key: 4281.key
tomb  .  A password is required to use key 4281.key
tomb  .  Password OK.
tomb  .  Key is valid.
tomb  .  New key: 4281.2ndkey
tomb  .  A password is required to use key 4281.2ndkey
tomb  .  Password OK.
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
device-mapper: remove ioctl on tomb.4281.1483380056.loop0 failed: Device or resource busy
Device tomb.4281.1483380056.loop0 is still in use.
tomb [E] Unexpected error in luksClose.

Let me know if any additional information is needed

**Comment by reiven** [comment]
Looks the problemas was the auto-mount of removable devices.

**Comment by jaromil** [comment]
are there ways to avoid such problems? I am interested to know in which conditions it occurs.

**Comment by reiven** [comment]
In some of the steps of the setkey process, before changing the keys itself, if you have the "removable devices" (which is normally default for ubuntu/mint) turned on, it automount the tomb, it fails to close it and ends up with error, even if the key was changed correctly

**Comment by jaromil** [comment]
it seems to be the dconf setting `org.gnome.desktop.media-handling`. Are there ways to read and set this setting from a script? I think tomb should check it, give a warning and eventually even switch it off and back on during operations. I am assuming there is no way to mark a device as excluded from automount..

**Comment by reiven** [comment]
Keep in mind that setkey is the only operation with this 'issue' , even tomb open do not trigger the automount.
