### ISSUE TITLE
Are you really using AES-256?

### ISSUE THREAD

**Issue by danvari** [dyne/Tomb#238]
Hey :),

I (and I guess others too) always thought that using 'luksFormat --key-size 256' implies AES-128 and not AES-256 (which would be --key-size 512). But in the key forging part you make use of 'AES256' for the GPG crypto. Can you please clarify this? The key itself is encrypted with AES256, but the underlying block crypto is done in AES128? Does this makes sense? Is this intended? Why don't you use AES256 for the block crypto?

**Comment by jaromil** [comment]
The block crypto cipher is `aes-xts-plain64:sha256` (unless customised in tomb's lock phase) with 256 bytes long keys.

The key is generated from `/dev/random` using ``dd`` to gather 256 bytes.

The key is symmetrically encrypted using `gpg --cipher-algo AES256` (unless customised at tomb's forge fase).

Hope this clarifies a bit. I'm not sure I understand your concern. Is there some documentation stating that `luksFormat --key-size 256` implies AES128 block cipher?

**Comment by danvari** [comment]
Have a look for example here:

https://en.wikipedia.org/wiki/Disk_encryption_theory#XEX-based_tweaked-codebook_mode_with_ciphertext_stealing_.28XTS.29

Quote:

"As a result, users wanting AES 256 and AES 128 encryption must supply of 512 bits and 256 bits of key respectively."

This is of course only true for XTS, which is what you use (and which is totally fine). But you really want to set the key size to 512 for the block crypto in order to get AES-256 in dmcrypt. Here is another hint:

https://wiki.archlinux.org/index.php/Dm-crypt/Device_encryption

"By default a 256 bit key-size is used. Note however that XTS splits the supplied key in half, so to use AES-256 instead of AES-128 you have to set the XTS key-size to 512."

**Comment by jaromil** [comment]
I see. You are right. I overlooked this detail when switching from CBC to XTS by default.
We shall update the key creation mechanism to elevate the size to 512 bytes and default to XTS AES256.
Thanks for your advice!

**Comment by danvari** [comment]
Great, thanks :), another source, which you can verify locally:

/proc/crypto:

...
name         : xts(aes)
driver       : xts-aes-aesni
module       : kernel
priority     : 400
refcnt       : 3
selftest     : passed
internal     : no
type         : ablkcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
ivsize       : 16
geniv        : <default>
...

The maximum keysize for aes-xts is 64 bytes (512 bit) and the maximum keysize for cbc-aes is 32 byte (256bit).

**Comment by mandeep** [comment]
@jaromil Will it be possible to forge new keys for existing tombs with the new key length?

**Comment by Narrat** [comment]
Well, the keys for tombs can be exchanged with "setkey", so it should be possible

**Comment by jaromil** [comment]
All considered, changing keys to bigger ones for existing tombs will not change the encryption algorithm used to format the tombs. This change affects only the `lock` command (luksFormat). So to have AES256 Tombs one would need to create a new tomb and key and copy all contents from the old to the new one.

**Comment by parazyd** [comment]
Applied on 9110ccd9d16c1cb25e9694cd426e299c0655f1da
