### ISSUE TITLE
generation of .mo files errors out

### ISSUE THREAD

**Issue by Narrat** [dyne/Tomb#240]
I am currently getting errors, when formatting the language files (noticed during installing those)

$ msgfmt -o ru.mo ru.po
ru.po:1151:55: invalid control sequence
ru.po:1155:55: invalid control sequence
msgfmt: found 2 fatal errors

and in case of the french translation:
$ msgfmt -o fr.mo fr.po
fr.po:1181:55: invalid control sequence
fr.po:1185:55: invalid control sequence
msgfmt: found 2 fatal errors

**Comment by jaromil** [comment]
How to reproduce the error? `msgfmt -o fr.mo fr.po` gives me no error, nor the ru.
Running on Devuan jessie, `msgfmt (GNU gettext-tools) 0.19.3`

**Comment by Narrat** [comment]
I'm trying it with HEAD.
Latest release should be fine.

Gettext version is 0.19.8.1

**Comment by gdrooid** [comment]
You're right, it's failing for me too on `msgfmt (GNU gettext-tools) 0.19.7`. I must have overlooked this on the last update. I'll fix it.

If you want to work with it meanwhile just search for `\$HOME` in the `.po` file and remove the backslash (`\`).

I wonder why the older version of `msgfmt` doesn't fail.

**Comment by gdrooid** [comment]
Fixed :) Thanks for reporting.

I also updated the `.pot` generation script to remove the conflicting backslash automatically (I used to do this by hand before committing 😓 ).

**Comment by jaromil** [comment]
well done! thanks everyone!
