### ISSUE TITLE
Unable to open tombs with wrapper

### ISSUE THREAD

**Issue by mandeep** [dyne/Tomb#241]
Hi all,

With Tomb 2.3 I am unable to resize a tomb. If I use the following command, I receive the error ```Key not found, specify one using -k.```:

```
tomb resize test.tomb -s 20 -k test.tomb.key
```

**Comment by jaromil** [comment]
Try to put `-k keyfile` before the resize command? curious, as position shall not be a problem... yet in the tests we have this which passes:
```
    tt --unsafe --tomb-pwd ${dummypass} -k /tmp/test.tomb.key resize /tmp/test.tomb -s 30
```
perhaps worth fixing and adding a test on option position

**Comment by mandeep** [comment]
I tried ```tomb -k test.tomb.key resize test.tomb -s 30``` and received the same error.

**Comment by mandeep** [comment]
@jaromil It seems that there were changes to Tomb 2.3 that affected the Python wrapper that I wrote as I was able to get Tomb 2.3 resize to work with new Tombs using Tomb. I'll investigate further and let you know what I find.

**Comment by jaromil** [comment]
are there any failing tests from the testuite in extras/test? just do make in that dir to run all tests.

**Comment by mandeep** [comment]
The tests seem to be okay. The only difference I could see between the tests I ran and the tests that are on Travis is the following snippet:
```
tomb [D] Identified caller: mandeep (1000:1000)
tomb [D] Tomb command: open /tmp/test.tomb
tomb [D] Caller: uid[1000], gid[1000], tty[/dev/pts/2].
tomb [D] Temporary directory: /tmp/zsh
tomb  .  Commanded to open tomb /tmp/test.tomb
tomb [D] is_valid_tomb /tmp/test.tomb
tomb [D] tomb file is readable
tomb [D] tomb file is a regular file
tomb [D] tomb file is not empty
tomb [E] Tomb is currently in use: test

```

**Comment by jaromil** [comment]
Is this right after the resize test block with header `Testing resize to 30 MiB`?

**Comment by mandeep** [comment]
No the resize tests passes correctly. This happens on ```Testing open with good password.```

**Comment by mandeep** [comment]
I've narrowed it down to the key creation and the key lock command. The key forge command I'm using is 
```
sudo --stdin tomb forge --unsafe --tomb-pwd password test.tomb.key
```

While the lock command is 
```
sudo --stdin tomb lock --unsafe --tomb-pwd password test.tomb -k test.tomb.key
```

Since this is a wrapper I'm having to use the --stdin, --unsafe, and --tomb-pwd flags.  Is anything immediately noticeable?

**Comment by mandeep** [comment]
@jaromil Is this intended behavior? If so I can close this issue.

**Comment by jaromil** [comment]
No, the intended behavior is that using the force flag in tomb `-f` the commands should succeed even with an unencrypted swap. As you wrote "_With the system with the unencrypted swap, -f or swapoff -a both cause errors with opening tombs._" I think this is a bug.

**Comment by mandeep** [comment]
Hi @jaromil, I just wanted to give you an update. I encrypted my swap partition and I'm still having problems with Tomb 2.3 stating a key file is not found. I've reverted back to Tomb 2.2 and everything seems to be okay. I'm not sure where to pinpoint the problem, but it seems that Tomb 2.3 does not like the commands I posted in the prior post.

**Comment by mandeep** [comment]
I've identified the cause for Mausoleum's erratic issues. The swap bug still exists however. I will close this issue since this was mostly about Mausoleum. Let me know if you would like me to open an issue regarding the unencrypted swap behavior.

**Comment by jaromil** [comment]
yes please, we need to keep an issue detailing the current problem encrypted swap! thanks
