### ISSUE TITLE
Non-writable Tomb file can't be opened even with "read only " mount option.

### ISSUE THREAD

**Issue by mesbahamin** [dyne/Tomb#247]
I'm trying to open a tomb file that's in a file system mounted as "read only".
Even when I use Tomb's `-o` option with `ro`, I am unable to open it. It seems
that Tomb requires the tomb file to be writable even when instructed to mount it
as read only.

Is this the desired behavior? Does Tomb need to write to a Tomb file in order to open it, even when it mounts it as read only?

I have a desired use case that is not possible with this behavior. I would be happy to investigate this further and submit a pull-request if that would be helpful.

## Steps to reproduce the behavior

Create a test Tomb file:

    $ tomb -s 128 dig test
    tomb  .	 Commanded to dig tomb test
    tomb (*) Creating a new tomb in test
    tomb  .	 Generating test of 128MiB
    128+0 records in
    128+0 records out
    134217728 bytes (134 MB, 128 MiB) copied, 0.631383 s, 213 MB/s
    -rw------- 1 amin users 128M Feb 11 13:18 test
    tomb (*) Done digging test
    tomb  .	 Your tomb is not yet ready, you need to forge a key and lock it:
    tomb  .	 tomb forge test.key
    tomb  .	 tomb lock test -k test.key

    $ tomb forge test.key 
    tomb  .	 An active swap partition is detected...
    [sudo] password for amin:
    tomb (*) The undertaker found that all swap partitions are encrypted. Good.
    mkdir: cannot create directory ‘/home/amin/.gnupg’: File exists
    tomb  .	 Commanded to forge key test.key with cipher algorithm AES256
    tomb [W] This operation takes time, keep using this computer on other tasks,
    tomb [W] once done you will be asked to choose a password for your tomb.
    tomb [W] To make it faster you can move the mouse around.
    tomb [W] If you are on a server, you can use an Entropy Generation Daemon.
    256+0 records in
    256+0 records out
    256 bytes copied, 0.000853655 s, 300 kB/s
    tomb (*) Choose the  password of your key: test.key
    tomb  .	 (You can also change it later using 'tomb passwd'.)
    tomb  .	 Key is valid.
    tomb  .	 Done forging test.key
    tomb (*) Your key is ready:
    -rw------- 1 amin users 513 Feb 11 13:19 test.key

    $ tomb lock test -k test.key
    tomb  .	 Commanded to lock tomb test
    tomb  .	 Checking if the tomb is empty (we never step on somebody else's bones).
    tomb  .	 Fine, this tomb seems empty.
    tomb  .	 Key is valid.
    tomb  .	 Locking using cipher: aes-xts-plain64:sha256
    tomb  .	 A password is required to use key test.key
    tomb  .	 Password OK.
    tomb (*) Locking test with test.key
    tomb  .	 Formatting Luks mapped device.
    tomb  .	 Formatting your Tomb with Ext3/Ext4 filesystem.
    tomb  .	 Done locking test using Luks dm-crypt aes-xts-plain64:sha256
    tomb (*) Your tomb is ready in test and secured with key test.key

Tomb file is writable by default, and can be opened successfully:

    $ ls -la
    total 129M
    drwxr-xr-x  2 amin users 4.0K Feb 11 13:19 .
    drwx------ 36 amin users 124K Feb 11 13:18 ..
    -rw-------  1 amin users 128M Feb 11 13:19 test
    -rw-------  1 amin users  513 Feb 11 13:19 test.key

    $ tomb -f -k test.key open test
    tomb  .	 Commanded to open tomb test
    tomb  .	 Valid tomb file found: test
    tomb  .	 Key is valid.
    tomb  .	 Mountpoint not specified, using default: /run/media/amin/test
    tomb (*) Opening test on /run/media/amin/test
    tomb  .	 This tomb is a valid LUKS encrypted device.
    tomb  .	 Cipher is "aes" mode "xts-plain64:sha256" hash "sha256"
    tomb  .	 A password is required to use key test.key
    tomb  .	 Password OK.
    tomb (*) Success unlocking tomb test
    tomb  .	 Checking filesystem via /dev/loop0
    fsck from util-linux 2.29.1
    test: clean, 11/32256 files, 9723/129024 blocks
    tomb (*) Success opening test on /run/media/amin/test

    $ tomb close test
    tomb  .	 Closing tomb [test] mounted on /run/media/amin/test
    tomb (*) Tomb [test] closed: your bones will rest in peace.

Remove the write permission from the Tomb file:

    $ chmod -w test

    $ ls -la
    total 129M
    drwxr-xr-x  2 amin users 4.0K Feb 11 13:19 .
    drwx------ 36 amin users 124K Feb 11 13:18 ..
    -r--------  1 amin users 128M Feb 11 13:21 test
    -rw-------  1 amin users  513 Feb 11 13:19 test.key

The Tomb file can't be opened, even when `ro` is passed as a mount option:

    $ tomb -f -k test.key open test
    tomb  .	 Commanded to open tomb test
    tomb [W] Tomb file is not writable: test
    tomb [E] Tomb command failed: open

    $ tomb -f -k test.key open test -o ro
    tomb  .	 Commanded to open tomb test
    tomb [W] Tomb file is not writable: test
    tomb [E] Tomb command failed: open

**Comment by jaromil** [comment]
Hi, thanks for raising the issue. This is not a desired behavior, but noone has looked into this particular use-case since long. I can see the reason to have a read-only mount of a tomb and think the best way possible can be that of intercepting the `ro` option in `-o` and bypassing checks in the mount operation, suspecting the error is when tomb tried to write the `.tty` and `.uid` files inside the tomb (I go by memory now, not reading the code...). If you have time and wish to contribute, be welcome to file a pull-req.

**Comment by mesbahamin** [comment]
Wonderful! I'll work on this today.

**Comment by jaromil** [comment]
Well done, you solved it brilliantly in PR #248. Thanks!
