### ISSUE TITLE
Misguided usage of /dev/random

### ISSUE THREAD

**Issue by darkfeline** [dyne/Tomb#253]
Using /dev/random for tomb forge is misguided. /dev/random and /dev/urandom both come from the same CSPRNG and there is no advantage to using /dev/random while there is a huge disadvantage in that it blocks.

See http://unix.stackexchange.com/a/324210 for more information.

**Comment by Narrat** [comment]
Similar thing was talked about in #117.
(Just a reference)

**Comment by Narrat** [comment]
Similar thing was talked about in #117.
(Just a reference)

**Comment by darkfeline** [comment]
What exactly was the conclusion reached in https://github.com/dyne/Tomb/issues/117?  That we would rather keep using /dev/random for good luck?  I guess that's fine as long as we're clear on the fact that there's no real benefit beyond potentially taking a lot more time and feeling good about ourselves.  The documentation stating that /dev/urandom is lower quality entropy and /dev/random is high quality entropy is also factually wrong.

**Comment by jaromil** [comment]
The conclusions so far are:
- keep status quo as blocking is more conservative about entropy
- recommend haveged installation (already present in docs)
- find some time to build support for getrandom() as in http://lists.openwall.net/linux-kernel/2014/07/17/235

In any case all options shall be kept open for choice.

**Comment by jaromil** [comment]
Also I add it would be rad to have an extras for entropy measurement, for instance using https://github.com/dyne/libdisorder

**Comment by darkfeline** [comment]
I'm not a cryptography expert, but using haveged is potentially worse than using /dev/urandom.  From what I've read, at worst using haveged compromises /dev/[u]random.

Here's an [article](https://lwn.net/Articles/525459/) that mentions misgivings about HAVAGE.

**Comment by jaromil** [comment]
Dear darkfeline, the intention of measuring the quality of random is orthogonal to your remarks.
Thanks about the link on haveged criticism, my colleague @parazyd already pointed me at that once.
But lets stick to the topic you opened, whose title is already opinionated enough: we do not have a "misguided use of /dev/random" just because we use a blocking source. A blocking source is supposedly blocking for lack of entropy, at least that's its rationale. Recommending to use non-blocking because "its the same" is a rather misguiding advice IMHO.

**Comment by jaromil** [comment]
Going beyond diverging opinions, please note the flag `--use-urandom` which is also documented in tomb's manpage. I'm closing this issue since its solved by the presence of this flag.

**Comment by boyska** [comment]
No @jaromil , the documentation is indeed misguiding. At https://github.com/dyne/Tomb/blob/master/doc/tomb.1#L35 it says
> low-quality random data (/dev/urandom)

 Similarly https://github.com/dyne/Tomb/blob/master/doc/tomb.1#L262 says

> Use an inferior quality random source to improve the speed of key generation at the cost of security (needed for the testing suite).

These sentences are wrong. They should be fixed

(and after they are fixed someone will ask "then why on hell is tomb using a slower random source that is no more secure?" when this happen, link to https://github.com/dyne/Tomb/blob/master/tomb#L263 ; but I'm digressing )

**Comment by jaromil** [comment]
You are right about the documentation, would you mind doing the fix? else I'll do.

**Comment by jaromil** [comment]
Actually I just made it, makes sense to have a less opinionated documentation and mention the `--dev-urandom` flag also in the `forge` command. Thanks for insisting :^)
