### ISSUE TITLE
Copy/paste doesn't work

### ISSUE THREAD

**Issue by javabeanz** [dyne/Tomb#257]
On Centos 7, copy pasting files onto the open tomb mounted fs doesn't work, "paste" option is disabled.

**Comment by roddhjav** [comment]
Did you set user permissions on your mounted folder:
```
sudo chown -R "${uid}:${gid}" "${path}"
sudo chmod 0711 "${path}"
```

**Comment by jaromil** [comment]
I'm still undecided if to restore those chown/mods to be set upon mount.
Its sort of handy for noobs but nasty for pros. Looking for opinions.

**Comment by javabeanz** [comment]
CENTOS automatically offers to open the newly mounted filesystem after
opening the tomb, and mounts them on /media/<tomb name> in my case
/media/secrets
I can modify the rights on this folder but that seems impractical if you
have to do that for each tomb.

**Comment by javabeanz** [comment]
Specifying a mountpoint and applying the chown commands dont help :
mount_tomb:135: permission denied: /mnt/win//.uid
mount_tomb:137: permission denied: /mnt/win//.tty
mount_tomb:140: permission denied: /mnt/win//.host
mount_tomb:144: permission denied: /mnt/win//.last

**Comment by Narrat** [comment]
Did you apply the chown commands before or after mounting the tomb?

**Comment by javabeanz** [comment]
i thought i already tried both but trying it again makes it work. mounting
works now without errors, and copy/paste too. thanks for your assitance.
