### ISSUE TITLE
missing lsof stuff

### ISSUE THREAD

**Issue by Narrat** [dyne/Tomb#258]
I started to address the issue of the missing tests back when lsof was reintroduced for slam.
As I don't know much about writing tests I would like to hear some input on what I need to think about etc

https://github.com/Narrat/Tomb/tree/missing_lsof_stuff
this branch holds currently 5 commits. Only two of them are related to lsof:

https://github.com/Narrat/Tomb/commit/8db76b659a0cb4637d253d4fe4c74d601f1cfd4c (should appear in --version)
https://github.com/Narrat/Tomb/commit/34dc689c87e21ab0570eb0546bbfaea31721114e (runtests)

The other three contain things I noticed, but can be ignored or cherry-picked if needed
https://github.com/Narrat/Tomb/commit/8f4a16d11fa88fd4e16ea16bf77a63b143f8aadc (whitespace in tomb)
https://github.com/Narrat/Tomb/commit/9e094ca13ac1b026fb76eadd17a0a93b964d308f (whitespace in runtests)
https://github.com/Narrat/Tomb/commit/11f0c38cb9830de6c1823bcc211a773ac52cef6b (qrencode in runtests)
_______
Currently my test scenario is really simple. Those are imo the things that should be done in the test.
Is there a common ground on what commands are available? To test slam I need some programs that uses the mount path. As I cannot know what user x has installed, even the use of xdg-open seems kinda risky.
Is it ok to specify the mount point? Else I would need to parse the tomb list command which is kinda ugly. Would be easier if findmnt would be available on most of the systems, as parsing the mount output could be also problematic?
Fail saves needed? Like to check first if program x is available and fail the test if not?

Aside from that, another question. Wouldn't it be easier to maintain the test if it was splitted into several files?
To make it possible to run one specific test if needed

**Comment by jaromil** [comment]
Good point about improving the modularity of tests, in progress on #259 thanks to Alexandre.

Meanwhile, answering your questions:
- I think that yes is OK to specify a mountpoint.
- For the running program in slam test I think writing a small C program that does `open()` then sleeps `argv[1]` seconds could be a clean solution.
- `findmnt` is in util-linux at least since 2014, it is OK to consider it present for the tests IMHO
- the whitespace cleanups are not going to be merged, too much going on. I like clean whitespace too but a commit that changes too much in the git history of tomb would be always distracting

**Comment by Narrat** [comment]
Ah, nice. Then I'm putting my work on hold until #259 is done.
And indeed, a simple C-program that comes with the testcase and does the blocking of the mount point makes the life easier. I will go that way.

**Comment by roddhjav** [comment]
Sorry for the the whitespace issue, it seems I'm at the origin of most (all) of the whitespace correction.

Regarding the tests in the future test suite #260, something like the following (untested) in `10_operations.sh` should work:
```sh
if test_have_prereq LSOF; then
    test_expect_success 'Testing functionality of the slam operation (use of lsof)' '
        mkdir $TMP/testmount &&
        tt_open $TMP/testmount --tomb-pwd $DUMMYPASS &&
        xdg-open $TMP/testmount/.last &&
        tt slam
        '
fi
```

**Comment by Narrat** [comment]
Thanks for the example.
The current WIP can be found here: https://github.com/Narrat/Tomb/tree/missing_lsof_stuff_2

https://github.com/Narrat/Tomb/commit/c658d33187cde764f7f2fd65f743e79be5d17e75 is still the same. Just enhancing --version.

https://github.com/Narrat/Tomb/commit/1e05ed573ccaa4ad90cbf3cb131ffc758e213ec5 contains the test.
Although there are currently some quirks.
One is the permission thing. Calling the binary as $USER is failing due to permissions on the tomb.
Secondly the test isn't running like it should, as the commands run sequentially. Any way to put it in the background so the next command is processed? Like a helper script which calls the binary, but that seems kinda ugly?

**Comment by roddhjav** [comment]
This is a working solution. I have tested it, it works.
```sh
if test_have_prereq LSOF; then
    gcc -Wall -o $TMP/close_block $TEST_HOME/close_block.c
    test_expect_success 'Testing functionality of the slam operation (use of lsof)' '
        mkdir $TMP/testmount &&
        tt_open $TMP/testmount --tomb-pwd $DUMMYPASS &&
        tt_set_ownership $TMP/testmount &&
        $TMP/close_block $TMP/testmount/occupied 20 &
        tt slam
        '
fi
```

* You need to set the user permissions on the tomb yourself. In the test suite, you can use the `tt_set_ownership` function.
* Use `&` instead of `&&` to put close_block in the background
* Do not forget to remove the `--chain-lint` option in `extras/test/Makefile` (`TEST_OPTS`) otherwise the tests will fail.

**Comment by Narrat** [comment]
Curious, as I tried it with only & to set it into the background but then an error appeared because of parsing and I interpret it as that there can only be the &&.
And thanks for the note on tt_set_ownership as I (obviously) totally missed it.

Regarding the last point I will get to it when I'm back at home (need to read some pages to understand the impact of this option)
