### ISSUE TITLE
[RFC] Use sharness as test suite

### ISSUE THREAD

**Issue by roddhjav** [dyne/Tomb#259]
The test suite in Tomb is handmade. It has for consequences that both the tests and the tests system need to be maintained. Moreover the tests themselves might be less complex and easier to maintain if we use a shell compatible test suite.

I did a few tests using the [sharness](https://github.com/chriscool/sharness) test suite [on my fork](
https://github.com/roddhjav/Tomb/tree/sharness/extras/test). The test output can be seen on [travis](https://travis-ci.org/roddhjav/Tomb).

As you can see, theses tests are a lot of easier to write/understand than the actual one.

As a showcase, right now I only implemented the following tests:
* Basic test (tomb creation, open & close).
* The tests related to the GPG keys, because I know them ;) 
* The regression tests.

I will implement the remaining test in the future if you like the proposition.

**Comment by jaromil** [comment]
Dear Alexandre, this looks great! I like it! indeed it becomes much more readable and maintainable with a rather small structural change from what we have now.

**Comment by roddhjav** [comment]
That's great, I'm going to continue working on the implementation of theses tests.

Meanwhile, I think test coverage could be added to the system too. I did it to [pass-tomb](https://github.com/roddhjav/pass-tomb) and it was quite useful. However, in pass-tomb I use [kcov](https://github.com/SimonKagstrom/kcov) that doesn't seem to work with zsh. Do you know a test coverage program compatible with zsh?

**Comment by jaromil** [comment]
There is no code coverage tool in zsh AFAIK. Interesting kcov, I suspect bash support may be tried on zsh scripts simply as is, have you tried?

**Comment by roddhjav** [comment]
Yes, I tried to run kcov on with tomb and it didn't work. (it is able to run tomb but not to get the code coverage).
