### ISSUE TITLE
Q: What happens to tombs if not closed or forgot to close it and then your reboot. Or what if there is a power cut?

### ISSUE THREAD

**Issue by tombraidr** [dyne/Tomb#263]
I started using Tomb. It is a great tool! Congrats!

So yeah. What happens if tomb is not closed or you forgot to close it and then reboot? Or what if there is a power cut? Would it be corrupted? Would it be secure? 

Sorry if this is not an issue. Thanks!

**Comment by jaromil** [comment]
Tomb uses Ext4 with journaling by default, so there should be no data loss even on dirty shutdowns without unmount. Such shutdowns have occurred to me many times through years of usage and I've never experienced a problem, merits of ext4...

**Comment by tombraidr** [comment]
@jaromil 

Good to know. Now my bones can rest assured. Thanks!
