### ISSUE TITLE
Confusing/misleading/scary messages after retrying a resize that went wrong because a mistyped password (phantom resizing?)

### ISSUE THREAD

**Issue by tombraidr** [dyne/Tomb#269]
So I try to resize and typed a wrong password. This happens:

```
tomb resize -s 3000 secret.tomb -k photo.jpeg

tomb  .  Commanded to resize tomb personal.tomb to 3000 mebibytes.
tomb  .  Valid tomb file found: secret.tomb
tomb  .  Key is an image, it might be valid.
tomb  .  Generating secret.tomb of 3000MiB
1000 blocks (1000Mb) written.
1000+0 records in
1000+0 records out
tomb  .  A password is required to use key photo.jpeg
tomb [W] Detected DISPLAY, but only pinentry-curses is found.
steghide: could not extract any data with that passphrase!
tomb [E] Wrong password or no steganographic key found
```
At this point I'm not sure what to do. There is no information about the status of the resizing. Did it went through? O did I just f*cked it up? I open the tomb and check its size: **It wasn't resized**.  Hmmm...So now what? Should I retry? What if I retry and then wipes out my data?

So I cross my fingers and, close the tomb and retry to resize again: 

```
tomb resize -s 3000 secret.tomb -k photo.jpeg

tomb  .  Commanded to resize tomb secret.tomb to 3000 mebibytes.
tomb  .  Valid tomb file found: secret.tomb
tomb  .  Key is an image, it might be valid.
tomb  .  Tomb seems resized already, operating filesystem stretch
tomb  .  A password is required to use key photo.jpeg
tomb [W] Detected DISPLAY, but only pinentry-curses is found.
tomb [W] Attempting key recovery.
tomb  .  Password OK.
tomb  .  opening tomb
secret: 4231/128000 files (0.7% non-contiguous), 485913/511488 blocks
resize2fs 1.42.5 (29-Jul-2012)
Resizing the filesystem on /dev/mapper/tomb.secret.1497882038.loop0 to 767488 (4k) blocks.
The filesystem on /dev/mapper/tomb.secret.1497882038.loop0 is now 767488 blocks long.
device-mapper: remove ioctl on tomb.personal.1497882038.loop0 **failed: Device or resource busy**
```
At this point I'm like FUUUUUUUUUUUUU-  Bye bye tomb :'( ' 

But when I open the tomb I see _the resizing has been applied_! In other words, **the resize was already done the first time around BUT doesn't show up as resized after opening it** !! 

Suggestions: 

- The error message  that comes after giving wrong password when resizing should be more informative (i.e. 'Wrong pass, retry resizing tomb again'). 
- The messages that comes after retrying an incomplete resize shouldn't be scary and/or should be more informative (i.e. Resized was already done. Tomb is ready to be opened') 

In any case the phantom resizing should be fixed. 

Thanks for your attention!

**Comment by jaromil** [comment]
First of all thanks for your patience and sharing your journey.

I haven't looked closely into it, but recall that long ago I have a similar experience and then put a check for the resize: if tomb already resized (dd appended) then run `resize2fs` on the volume to extend the partition.
Perhaps this should be explicitly stated: that resize is half way but nothing is lost (there is no risk for the data in these operations) and that the resize command can be re-run to complete the operation. I believe this is the corner-case we are looking at.
There is a further complication in the way which is a problem closing the loopback device on the 1st resize failure.
