### ISSUE TITLE
call to exec_safe_func_hooks() fails

### ISSUE THREAD

**Issue by warkruid** [dyne/Tomb#271]
I upgraded tomb a couple of days ago.
First I noticed that the post-hooks was changed to exec-hooks.
Ok, I can live with that. But then I noticed that a call to exe_safe_func_hooks barfed

 exec_safe_func_hooks open ${tombmount}

...
exec_safe_func_hooks() {
    # Only run if post-hooks has the executable bit set
    [[ -x $mnt/exec-hooks ]] && {
        _success "Exec hook: ::1 exec hook:: ::2 action:: ::3 argument::" \
				 "${mnt}/exec-hooks" "$1" "$2"
        $mnt/exec-hooks "$1" "$2"
		return $?
    }
	return 0
}

The variable $mnt  doesn't get set

I suspect the variable $mnt must be changed to $2

**Comment by jaromil** [comment]
Thanks for reporting this. Yes this was a recent change and is not yet in stable as we wanted to run it through a bit and see reactions also re: change of function name.

**Comment by jaromil** [comment]
Should be fixed now and in the upcoming 2.5.

Thanks for your patience :^P took a long while to fix, but I'm sure you did on your own already.

**Comment by warkruid** [comment]
Thanx!  I did indeed patch it, but it is a pain to reapply that patch each time you upgrade :-)
Much better this way.
