### ISSUE TITLE
All drives wake from sleep when opening a tomb

### ISSUE THREAD

**Issue by wizbox** [dyne/Tomb#272]
I am using tomb with pass-tomb plugin for pass. When I open a tomb there is a 15-20 second delay while every single drive on my box wakes from sleep, including attached usb drives, then the tomb eventually opens. No data is spanned across these drives, I'm not sure why they need to be woken from sleep?

**Comment by jaromil** [comment]
Can you run `tomb -D` and point out in what stage of the command tomb exactly hangs? Thanks!

**Comment by jaromil** [comment]
Hi there and HNY :^) @roddhjav do you have any clue if this is a pass-tomb issue or tomb's?

I would really like to make sure this doesn't happens. Opening a tomb shouldn't wake up all drives connected and cannot see how this can happen.

**Comment by roddhjav** [comment]
Without debugging output, it's hard to tell. @wizbox you can use pass tomb/open/close with the `-D` option to show tomb debug messages.

I don't think it comes from pass tomb because I would have seen this issue in the test suite. That said I would have seen this issue in the tomb test suite too.

**Comment by jaromil** [comment]
OK. I'm not sure how this issue can be visible in the test suites? an HD spinning up can be caused by a read-only operation on other mounted volumes, I guess. Or is the simple invokation of `mount -l` causing it?
