### ISSUE TITLE
Tomb closing fails when mounted on a binded directory

### ISSUE THREAD

**Issue by gador** [dyne/Tomb#273]
Hi,

Tomb yields an error when the mount point is on a binded directory and will fail, leaving a decrypted loop device. I wrote a detailed blog post about the problem [1]. To summarize it:

1) I use Qubes OS[2]. This comes with some not-standard folder setups. One of them is bind-mounting the /home directory to /rw (This is necessary because of the underlying architecture. /rw keeps the persisting changes of the virtual application VM.)
2) Apparently, when mounting on a bound directory, it appears twice in the output of mount. (In this example once for /home/user/mountpoint and once for /rw/home/user/mountpoint)
3) When Tomb closes the tomb it searches for bound tomb directories and falsely identifies one of the above directories as a bound directory. (This is largely due to Linux horrible bound mount management, namely a non-existing one. There is seriously no reliable way (that I've found) to detect a bound directory)
4)Tomb now umounts the (wrongly identified) bound directory. It umouts successfully and obviously both entries disappear from the mount output.
5) In the next step, Tomb tries to umount the actual /dev/mapper/tomb.. and fails, since it was already umounted.
6) Tomb exists with an error, leaving /dev/mapper/tomb.. in a decrypted state. 

Yes, this is somehow Qubes OS specific, but when the Tomb directory is mounted on another bound directory, the same error will happen. 

Regards,

Florian Brandes 

[1]: https://gador.github.io/debugging-pass-tomb-on-qubes-32.html
[2]: https://www.qubes-os.org/

**Comment by jaromil** [comment]
hi Florian, thanks for the detailed report! indeed QubeOS2 specific, but worthed supporting.

Also I am aware of the "Linux horrible bound mount management" issue, facing it in Tomb where even a simple change in the `mount` output may break our tool. Lets keep eyes peeled for better solutions in any case.

I suspect the only reason you PR breaks is trivial and not related to your changes, but to a bug hanging around the make lint command since a short while (perhaps introduced by a change in Travis base OS).

**Comment by gador** [comment]
Yes, it appears, like all your tests pass:
>make aggregate-results
>make[3]: Entering directory `/home/travis/build/dyne/Tomb/extras/test'
>for f in test-results/*.counts; do \
>		echo "$f"; \
>	done | '/usr/bin/zsh' 'aggregate-results'
>
>fixed   0
>success 40
>failed  0
>broken  0
>total   40

Seems indeed like a problem with Travis

**Comment by jaromil** [comment]
Fixed in #275
