### ISSUE TITLE
Abillity to delete a tomb

### ISSUE THREAD

**Issue by IvanX507** [dyne/Tomb#277]
Hi, I wanna delete a tomb that I'm not gonna use but i don't find a option to do that in the tomb commands.
Theres an option or it hasn't it?.
In the case that the option doesn't exist, theres a way for delete it?.

**Comment by parazyd** [comment]
If the tomb is closed and not mounted, you can just `rm <tombname>` to delete it.

**Comment by jaromil** [comment]
Depending from the size of the tomb, it may take longer (fine-tuning possible) also `wipe` and `srm` can be considered. The tomb must be closed before deletion.

**Comment by IvanX507** [comment]
Thanks for the help!
