### ISSUE TITLE
Q: What happens when you remove files from a Tomb via a file explorer? Do they leave traces on local host?

### ISSUE THREAD

**Issue by tombraidr** [dyne/Tomb#278]
I might be wrong but I noticed when I delete files from a Tomb using Nautilus (file explorer on Debian) they go to the Nautilus' 'Wastebasket' and a registration of deleted files also shows up in a hidden folder ('.Trash-1000') inside the Tomb . So it seems to me the local host is registering Tomb files as deleted. This doesn't look safe to me, does it? If they do leave traces in your local host it would be great the deletion  registration only just shows up in the '.Trash-1000' folder inside the Tomb.

Or is matter of just not deleting files via Nautilus?

**Comment by jaromil** [comment]
Knowing the fallacity of the Nautilus software in general, I personally recommend to never use it. I find it very irresponsible for distributions to ship it as default, it is an unsafe feature-creeping enormous application with privilege escalation in place. However, if one needs to use it, then do not use it for Tombs.

In case you discover a way to disallow this behavior in Nautilus when operating inside a Tomb, like a setting of sorts, then please let me know, I'd be very interested. Unfortunately having studied a bit freedesktop's standards I have found very little documentation on how to integrate an externally mounted resource into their workflow. But then I'm really not an expert on these matters, I just regard the whole application stack as something to be avoided.

**Comment by Narrat** [comment]
Using Nautilus, Thunar and else for interacting with tombs can be revealing. 
For example thumbnail preview. Those are saved per default in the home folder (.thumbnails or .cache/Thumbnails). 
So other features can also leave traces

**Comment by tombraidr** [comment]
Very good points, @jaromil  and @Narrat 

You are right. Nautilus and Tomb are a no no.  Unfortunately I noticed this behavior perhaps too late.

 Wouldn't be great if Tomb site had some sort of a Safe Guide (Read Me First) to make us aware or at least mention all these sorts of situations that make the use of Tomb unsafe?

**Comment by tombraidr** [comment]
@jaromil 

I know this question is outside of Tomb scope, so my apologies,  but do you know of any secure and safe alternative to Nautilus and et al? Thanks!

**Comment by Pawamoy** [comment]
@tombraidr I guess the issue here comes from graphical File Managers which use thumbnails and wastebaskets, so why not a terminal (text) -based file manager like [ranger](http://ranger.nongnu.org/) 😃 ? I am not aware of its level of security and if using it with Tomb is better than another FM though!

**Comment by Narrat** [comment]
Even those can be unsafe. Although I didn't use ranger, just knowing it exists, I can tell about vifm. 
Normal deletion of files moved those into a subfolder in the home directory, so to make it possible to undo the deletion. 
Can't describe how surprised I was when I stumbled upon those (and reading the doc would have told me so *cough*)

**Comment by jaromil** [comment]
I use ranger (mentioned by @Pawamoy) but also `pcmanfm` is very good, esp. when file selection is limited to drag&drop operations it comes at hand and doesn't add any clutter.

**Comment by tombraidr** [comment]
Thanks, everybody. Very informative thread. I'm closing this down.
