### ISSUE TITLE
Issue creating Keyfile for tomb

### ISSUE THREAD

**Issue by usmarine2141** [dyne/Tomb#279]
$ sudo tomb forge -k fck.tomb.key fuckfuckfuck
tomb  .  An active swap partition is detected...
tomb [W] This poses a security risk.
tomb [W] You can deactivate all swap partitions using the command:
tomb [W]  swapoff -a
tomb [W] [#163] I may not detect plain swaps on an encrypted volume.
tomb [W] But if you want to proceed like this, use the -f (force) flag.
tomb [E] Operation aborted.

What is going on here? 

I try running swapoff -a 

$ tomb forge -k fck.tomb.key test swapoff -a 
tomb [E] Unrecognized option -a for subcommand forge

**Comment by usmarine2141** [comment]
if i use the -f flag, will it work properly?

**Comment by usmarine2141** [comment]
i used the -f tag and it created it but appears i have to run it as sudo. as it doesnt mount... is this normal usage?

$ tomb open -k secretc.tomb.key test.tomb -f
tomb  .  Commanded to open tomb test.tomb
tomb  .  Valid tomb file found: test.tomb
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /media/test
tomb (*) Opening test on /media/test
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha256"
tomb  .  A password is required to use key secretc.tomb.key
tomb  .  Password OK.
tomb (*) Success unlocking tomb test
tomb  .  Checking filesystem via /dev/loop0
fsck from util-linux 2.29.2
test: clean, 11/2048 files, 1362/8192 blocks
tomb (*) Success opening test.tomb on /media/test
mount_tomb:135: permission denied: /media/test/.uid
mount_tomb:137: permission denied: /media/test/.tty
mount_tomb:140: permission denied: /media/test/.host
mount_tomb:144: permission denied: /media/test/.last

**Comment by usmarine2141** [comment]
when using sudo i get this output


$ sudo tomb forge -k test.tomb.key -f
tomb  .  Commanded to forge key test.tomb.key with cipher algorithm AES256
tomb  .  Using KDF to protect the key password ( rounds)
tomb [W] This operation takes time, keep using this computer on other tasks,
tomb [W] once done you will be asked to choose a password for your tomb.
tomb [W] To make it faster you can move the mouse around.
tomb [W] If you are on a server, you can use an Entropy Generation Daemon.
379 blocks (0Mb) written.
512 blocks (0Mb) written.
512+0 records in
512+0 records out
tomb (*) Choose the password of your key: test.tomb.key
tomb  .  (You can also change it later using 'tomb passwd'.)
No $DBUS_SESSION_BUS_ADDRESS found, falling back to curses
No $DBUS_SESSION_BUS_ADDRESS found, falling back to curses
tomb  .  Key is valid.
tomb  .  Done forging test.tomb.key
tomb (*) Your key is ready:
-rw------- 1 root root 769 Aug  7 22:10 test.tomb.key

**Comment by usmarine2141** [comment]
if i go into gparted and rt click on my swap off it buids with no errors, but cannot create folders in the tomb

**Comment by usmarine2141** [comment]
I think i got it figured out. I have to sudo my file manager to make files/folders in my tomb

**Comment by jaromil** [comment]
you're good with all this, its all normal behaviour, perhaps too verbose or paranoid, but all your pasted output indicates success. DBUS errors are due to pinentry invokation on your distro. We'd rather not hide anything like that anyway. And yes, most tomb commands require sudo (we may want to make this more noticeable in the docs).
