### ISSUE TITLE
support cloakify for key storage

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#286]
Awesomeness beyond steganography: https://github.com/TryCatchHCF/Cloakify

**Comment by heat-wave** [comment]
I would love to contribute to tomb, but I have questions regarding the implementation as there's no specifics (sorry if they are dumb).

- Should **cloakify** be an alternative option to **bury** or a suboption of it?
- Is there supposed to be any processing of cloakify's output or is that the desired format?
- Most importantly, cloakify doesn't exist in pip and has no system-wide installer. So unless the user puts cloakify/decloakify on their path, what's the cleanest way to ensure that the tool is available?

**Comment by jaromil** [comment]
hi! thanks for your interest :-)
1. I guess a suboption of bury
2. Output from cloakify should be the final key format
3. it should go in extras/ as source form, detected at runtime
