### ISSUE TITLE
Why skipping bind-hook if target is not existent?

### ISSUE THREAD

**Issue by Pawamoy** [dyne/Tomb#287]
Is it a `mount -o bind` limitation?

I don't want to create an empty file in my home just for it to be bound. 😕

**Comment by jaromil** [comment]
It is meant to be skipped, to make users more aware of what is happening. The tomb script is not meant to modify anything on the host file system beyond creating and modifying tombs and keys.

**Comment by Pawamoy** [comment]
Okay, I see that mount will refuse to bind if the target does not exist, and I understand that tomb should then not `touch` or `mkdir` the targets. I will create the empty files / directories myself, thanks!
