### ISSUE TITLE
list_gnupg_ciphers() fails with non english locales

### ISSUE THREAD

**Issue by Narrat** [dyne/Tomb#299]
The output of gpg --version is localized, so the search for Cipher may fail and provide no output in tomb -v.
Dunno atm how to handle this, as there doesn't seem to be a --list-ciphers like option in gpg?
And dunno how nice it is, to prepend the gpg command with LANG=C

**Comment by jaromil** [comment]
does it works by prepending LANG=C inside the backtick at line 1365?

**Comment by Narrat** [comment]
Yeah, it does work, but is it a nice way to solve this in such a way? (Else I would have created a PR.)

But imo the whole thing could see some love?
Like there is a small formatting issue in the output (missing a space in front), and the construct itself. Does it really make sense to include the binary path? And if it make sense it should be placed differently. It isn't a key forging algo.

```
  gpg (GnuPG) 2.2.4 - key forging algorithms (GnuPG symmetric ciphers):
  /usr/bin/gpg
 IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256
```
Maybe all (hard deps and opt deps) should display the version (if found), display only the binary path or both. Personally I would favor displaying the version.

**Comment by jaromil** [comment]
I'd prefer less cruft but you are welcome to make a PR then!
