### ISSUE TITLE
Support pitchforkedsphinx for password handling

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#306]
by stef, see https://github.com/stef/pitchforkedsphinx

**Comment by heat-wave** [comment]
What is the scope of password handling expected here? Supporting 'get' operation will be relatively straightforward, while other operations can be more clunky. What I currently have in mind is adding **--sphinx-host** and **--sphinx-username** parameters to operations involving **ask_password** (an obvious example is **open**), and using pinentry to receive the master password for sphinx.

**Comment by jaromil** [comment]
I think that's it, mostly. Perhaps we can also facilitate to put a key's password into sphinx?

**Comment by heat-wave** [comment]
This can be done, although I believe it's important not to make this confusing to the user. There's two distinct passwords: _master_ (human-memorizable) and _generated_ (for lack of a better word; high-entropy, hard to remember) using the aforementioned master. Using the key's password as master serves no purpose.

We can try to make this seamless for the user (apart from configuring the oracle location for pwdsphinx): if they use the sphinx option, the password that we're asking when creating the tomb will serve as master for sphinx, and the result of the sphinx operation will serve as actual password of the key. Then unlocking follows the same logic and there's no confusion. Host and username parameters should still be left to the user (I would advise against auto-generating those on their behalf).

**Comment by jaromil** [comment]
ACK. Some remarks
1. `master` : `generated` = `password` : `key` (euclidean comparison with Tomb's key system)
2.  the host-username pair shouldn't be used to generate secrets, since tombs are portable across systems, or is there no problem?
3. I don't think that a sphinx-made `generated` should be the `password` of a tomb key: I think that the tomb `key` is substituted with sphinx-made `generated` and that the `master` becomes the `password`.

What do you think? I think 3. simplifies a lot for the user, but I'm insecure about 2. (have to look more into sphinx, grateful for your insights)

**Comment by heat-wave** [comment]
1. Noted.
2. Host and username are not system-specific, these are the values that allow the user to distinguish between various stored passwords (and since the storage itself isn't aware of its contents, this is necessary). Actual hostname and username of the user making the call don't matter here.
3. This does indeed remove a step from the process. AFAIK, the output format of sphinx is always a 40-character ASCII string. Do we then use it as TOMBSECRET to directly open/close tombs? Maybe I am too used to the standard keys and got confused here.

**Comment by jaromil** [comment]
2. Noted :^)

we are left with the last point then:

yes the decrypted content of the key file is then the content TOMBSECRET pipes into cryptsetup (and is never saved on any support) and that is the actual key material used by cryptsetup, which also performs hashing and KDF on it AFAIK. If sphinx provides only 40 bytes this is somehow bad, since it is indicated (I don't know exactly where now sorry) to use keys long 512 bytes with cryptsetup in `aes-xts-plain64` mode which is the default in Tomb (and AFAIK the most reliable in cryptsetup).

It is worth investigating if using keys of 40 bytes really degrades a lot the security of the tomb.

**Comment by heat-wave** [comment]
If I'm not mistaken, the 512 bit requirement is due to XTS using half of the cipher, so to achieve 256 bit encryption, we need twice as much. From sphinx description it looks like 40 character is the longest we can get I'm afraid. In that case, it's worth considering whether the use case I initially proposed is viable at all. Again, I rely on your judgment in these matters.

**Comment by jaromil** [comment]
Yes, I agree your initial use case is the best viable approach: having sphinx provide the `password` for the tomb's `key`. I'm glad we bashed the idea around a bit, seems to hold well :^)

**Comment by heat-wave** [comment]
As an update, the sphinx integration functionality is close to ready, but testing it on travis doesn't seem possible. Dependency chain is as follows: pwdsphinx->libsphinx->libsodium/libsodium-dev. libsodium headers provided in **trusty** and **xenial** repos are too old and don't have the necessary code, and low-level dependencies don't let us just install libsodium from newer ubuntu repos. As of now, travis hasn't accepted **bionic**, let alone **disco**. Is there anything to be done to mitigate this problem?

**Comment by jaromil** [comment]
Sure: travis supports docker images. Try on this one, should have recent deps:
```
docker run -it dyne/devuan:beowulf
```
if you make a Dockerfile to run the tests I'll set it up in travis.
