### ISSUE TITLE
Security issue when using tomb + kdf

### ISSUE THREAD

**Issue by AitorATuin** [dyne/Tomb#307]
When using KDF support, passwords containing whitespaces are trimmed out without even notifying the user (in any case since without KDF users can have passwords containing whitespaces, when using KDF users should be able to use them as well). 

Easy to reproduce, see this snippet:

```
% salt=$(./bin/tomb-kdb-pbkdf2-gensalt)
% iter=$(./bin/tomb-kdb-pbkdf2-getiter)

% ./bin/tomb-kdb-pbkdf2 ${salt} ${iter} 64 2>/dev/null <<<'one two three'
fd144a3923ed7bc5a5e04a1b7ec4d69d1edb71da5aa9f0acc4715beeb51690c8b5c300cc47bcb6b05ccde1447d24a5a408c13362bdee167702f939763ab93120

% ./bin/tomb-kdb-pbkdf2 ${salt} ${iter} 64 2>/dev/null <<<'one crappy shit here'
fd144a3923ed7bc5a5e04a1b7ec4d69d1edb71da5aa9f0acc4715beeb51690c8b5c300cc47bcb6b05ccde1447d24a5a408c13362bdee167702f939763ab93120

% ./bin/tomb-kdb-pbkdf2 ${salt} ${iter} 64 2>/dev/null <<<'one'
fd144a3923ed7bc5a5e04a1b7ec4d69d1edb71da5aa9f0acc4715beeb51690c8b5c300cc47bcb6b05ccde1447d24a5a408c13362bdee167702f939763ab93120
```

As you can see passwords are 'parsed' before inputting them into `gcry_kdf_derive` function.

The problem seems to be exactly here: https://github.com/dyne/Tomb/blob/master/extras/kdf-keys/pbkdf2.c#L108

`fscanf` should be avoided!

Possible solutions:

Using fgets instead:

`fgets(pass, BUF_SIZE, stdin);`

Reading char by char from the input:
```
   int j = 0;
   while (j < (BUF_SIZ + 1)) {
       char c = getchar();
       if (c == EOF) break;
       pass[j] = c;
       j++;
   }
   if (j == BUF_SIZ + 1) {
       fprintf(stderr, "Error: password is too long\n");
       exit(1);
   }
   pass[j-1] = '\0';
```

**Comment by boyska** [comment]
I wrote that file in 2e6a3d, and I can confirm that the bug you reported is true, as I should have noted reading `man scanf`, which, describing the `%s` modifier says:

> Matches a sequence of non-white-space characters; the next pointer must be a pointer to the
> initial element of a character array that is  long  enough  to
> hold the input sequence and the terminating null byte ('\0'), which is added automatically. 
> The input string stops at white space or at the maximum field
> width, whichever occurs first.

Thanks for reporting (and fixing).
