### ISSUE TITLE
Tomb won't close when mount path contains spaces

### ISSUE THREAD

**Issue by fullmontis** [dyne/Tomb#315]
The response is the following: 
```
tomb close
tomb  .  Closing tomb [tombsession] mounted on /path with/spaces
tomb [W] Tomb was already umounted, possibly through a binded directory
Device tombloop is still in use.
tomb [E] Error occurred in cryptsetup luksClose tombloop
```

The tomb is not umounted already, and it should be seen by the program, but it isn't.

Replicate:
- mount tomb in a pathname containing spaces
- run "tomb close" to attempt closing
- the program will leave the tomb open
- remove space from path and rerun the closing command
- the tomb will now close

Using tomb 2.5, zsh 5.4.2

After some digging it appears the culprit is the following line: 
https://github.com/dyne/Tomb/blob/8d698ad46aa11d45880d2bc00f2d631608fe46a6/tomb#L2656

The grep command seems to return 1 (not found anything) although the $tombmount variable is correct. 

For some reason, replicating the code in bash works as expected, but doing this in zsh seems to not work. I am not sure as to why, nor how to correct it.

**Comment by jaromil** [comment]
Hi @fullmontis ! Thanks for the detailed report! looks like you found a bug. I'll look into this ASAP. Hopefully very soon now, lining it up with some other things pending.
