### ISSUE TITLE
Suggestion: remove the term "military-grade encryption"

### ISSUE THREAD

**Issue by hiqua** [dyne/Tomb#319]
I'm not sure whether this term is used ironically, but I think it currently reflects badly on this project. See for instance:

* https://www.quora.com/How-is-military-grade-encryption-defined
* https://www.reddit.com/r/crypto/comments/3rhcpu/what_is_a_basic_outline_of_militarygrade/
* https://hn.algolia.com/?query=military-grade%20encryption&sort=byPopularity&prefix&page=0&dateRange=all&type=comment

Saying that Tomb uses the same encryption as some other mainstream operating systems (most Linux distributions?) would be more convincing.

**Comment by jaromil** [comment]
You are right, actually the section on ISO is simply more detailed (robustness is not only about the mathematical model, but also how keys are handled etc.). thanks
