### ISSUE TITLE
Seemingly meaningless error messages

### ISSUE THREAD

**Issue by stevelitt** [dyne/Tomb#324]
Here's the last part of tomb open -D -k tc.tomb.key tc.tomb

fsck from util-linux 2.32.1
tc: clean, 11/9760 files, 6115/38912 blocks
tomb [D] Tomb engraved as tc
tomb (*) Success opening tc.tomb on /media/tc
_update_control_file:7: permission denied: /media/tc/.uid
chown: cannot access '/media/tc/.uid': No such file or directory
tomb [D] updated control file /media/tc/.uid = 1000
_update_control_file:7: permission denied: /media/tc/.tty
chown: cannot access '/media/tc/.tty': No such file or directory
tomb [D] updated control file /media/tc/.tty = /dev/pts/10
_update_control_file:7: permission denied: /media/tc/.host
chown: cannot access '/media/tc/.host': No such file or directory
tomb [D] updated control file /media/tc/.host = mydesk
_update_control_file:7: permission denied: /media/tc/.last
chown: cannot access '/media/tc/.last': No such file or directory
tomb [D] updated control file /media/tc/.last = 1538556748
tomb [D] bind-hooks not found in /media/tc
[slitt@mydesk junk]$

And indeed, there are no such directories, but /media/tc is mounted normally:
[slitt@mydesk junk]$ ls -ladF /media/tc/.*
drwxr-xr-x 3 root root 1024 Oct  3 04:52 /media/tc/./
drwxr-xr-x 3 root root 4096 Oct  3 04:49 /media/tc/../
[slitt@mydesk junk]$

So these are misleading error messages, unless .uid, .tty, .host and .last MUST be in /media/tc.

The following shellscript produces this error, assuming all the necessary tweaks are in /etc/sudoers:
#!/bin/sh
rm tc.tomb*
tomb dig -s 40 tc.tomb
ls -lh tc.tomb
tomb forge -k tc.tomb.key tc.tomb
tomb lock -k tc.tomb.key tc.tomb
tomb open -D -k tc.tomb.key tc.tomb

**Comment by somospocos** [comment]
Probably related:

    $ tomb -v
      Tomb 2.5

When following the basic usage steps from https://www.dyne.org/software/tomb/, the

    $ tomb open secret.tomb -k secret.tomb.key

step produces the following output:

    tomb (*) Success opening secret.tomb on /media/secret
    _update_control_file:7: permission denied: /media/secret/.uid
    chown: cannot access '/media/secret/.uid': No such file or directory
    _update_control_file:7: permission denied: /media/secret/.tty
    chown: cannot access '/media/secret/.tty': No such file or directory
    _update_control_file:7: permission denied: /media/secret/.host
    chown: cannot access '/media/secret/.host': No such file or directory
    _update_control_file:7: permission denied: /media/secret/.last
    chown: cannot access '/media/secret/.last': No such file or directory

If I close the tomb then open it again, these messages disappear. I suppose these files are created during the first run, so a simple check if they exist before attempting to chown them should fix it.

**Comment by Narrat** [comment]
A check is theoretically in place. Or more specific, it shouldn't be necessary if I look at `_update_control_files`. 
Those specific files would be created directly before the chown call. So due to permission issues, the files won't be generated on the first run?

**Comment by 68420948** [comment]
I stumbled over this issue while packaging tomb for Debian.
IMHO these errors results from the fact that a freshly generated tomb is owned by root, so that an initial user cannot write the control files. Please take a look at the bug opened at Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931027

I believe this patch solves the problem:
https://salsa.debian.org/pkg-security-team/tomb/blob/debian/master/debian/patches/fix-errors-on-open.patch

Cheers,
Sven

**Comment by jaromil** [comment]
Thanks, I like the approach. Source has changed and this patch should be applied around line 2190 in `_update_control_file()`.
BTW, I would love to get rid of the `chown`, but can't see any way around it.

**Comment by jaromil** [comment]
Thanks for updating Tomb's package, hope it gets in buster, because tomb 2.5 doesn't works with cryptsetup 2.1 and we'd be flooded with bugs about it.

**Comment by 68420948** [comment]
Buster has been in deep freeze for quite some time and still it is. No
more chance to get any updates from upstream into it before the
release, I am afraid. Maybe we can do a backport to Buster after it
became the new stable version.

Cheers,
Sven

**Comment by 68420948** [comment]
> BTW, I would love to get rid of the `chown`, but can't see any way
> around it.

I cannot see a way to eliminate this either.

In the case of a tomb opened with the -p option for/in use by different
users it's a must to hand the control files to the recent user as they
are owned by the previous user at the moment of opening the tomb.

Cheers,
Sven
