### ISSUE TITLE
Semiphore messages

### ISSUE THREAD

**Issue by stevelitt** [dyne/Tomb#325]
semid 9273344: semop failed for cookie 0xd4d9cac: incorrect semaphore state
Failed to set a proper state for notification semaphore identified by cookie value 223190188 (0xd4d9cac) to initialize waiting for incoming notifications.

This happens often when you tomb lock. Perhaps it happens on other functions also. This message turns out to be harmless, and happens when everything's going perfectly. But it reduces user confidence in a program that already has some misleading content.

This message seems to  indicate yet another try to get possession of a file. If so, and if you have control over the software writing this message, it should say "seeking control of file whatever",  not something with the word "failed" in it.

**Comment by jaromil** [comment]
wow, never seen that. is it in syslog or dmesg?
