### ISSUE TITLE
tomb lock stops at LUKS formatting

### ISSUE THREAD

**Issue by RuyBlast** [dyne/Tomb#328]
Hi,
I downloaded tomb (2.4, and I tried also 2.5) and I fail locking my first tomb, which makes me so sad as it looks very cool.
I am on an Ubuntu 16 laptop with:
  sudo 1.8.16
  cryptsetup 1.6.6
  pinentry-gnome3 (pinentry) 0.9.7
  gpg (GnuPG) 1.4.20
as requirered.
I ran exactly:

$ tomb dig -s 10 secrets.tomb
$ sudo swapoff -a
$ tomb forge secrets.tomb.key

without any problem, and then:

$ tomb lock secrets.tomb -k secrets.tomb.key
tomb  .  Commanded to lock tomb secrets.tomb
tomb  .  Checking if the tomb is empty (we never step on somebody else's bones).
tomb  .  Fine, this tomb seems empty.
tomb  .  Key is valid.
tomb  .  Locking using cipher: aes-xts-plain64:sha256
tomb  .  A password is required to use key secrets.tomb.key
tomb  .  Password OK.
tomb (*) Locking secrets.tomb with secrets.tomb.key
tomb  .  Formatting Luks mapped device.

And it stays forever (more than one hour) like that, with seemingly no tomb job consuming resources  ($ top).

If you have any insight about this failure, I thank you in advance for your help :)

**Comment by Narrat** [comment]
Hello.
Did you try a bigger tomb size? It shouldn't be a problem with 10MB, but who knows.
And could you run the lock command with -D for debug output? Maybe something interesting will appear in the additional output.

**Comment by RuyBlast** [comment]
Thanks Narrat for your advices.
I just tried 100MB (it behaves the same way), with -D argument. I still do not see the problem but in case, here are the logs:

$ tomb lock secrets.tomb -k secrets.tomb.key -D
tomb [D] Identified caller: milan (1000:1000)
tomb [D] Tomb command: lock secrets.tomb
tomb [D] Caller: uid[1000], gid[1000], tty[/dev/pts/18].
tomb [D] Temporary directory: /tmp/zsh
tomb  .  Commanded to lock tomb secrets.tomb
tomb [D] Tomb found: secrets.tomb
tomb [D] Loop mounted on /dev/loop0
tomb  .  Checking if the tomb is empty (we never step on somebody else's bones).
tomb  .  Fine, this tomb seems empty.
tomb [D] load_key argument: secrets.tomb.key
tomb [D] load_key: secrets.tomb.key
tomb [D] is_valid_key
tomb  .  Key is valid.
tomb  .  Locking using cipher: aes-xts-plain64:sha256
tomb  .  A password is required to use key secrets.tomb.key
tomb [D] asking password with tty=/dev/pts/18 lc-ctype=fr_FR.UTF-8
tomb [D] using pinentry-x11
tomb [D] get_lukskey
tomb [D] Created tempfile: /tmp/zsh/1923119823928826384
tomb [D] gpg: données chiffrées avec AES256
tomb [D] [GNUPG:] NEED_PASSPHRASE_SYM 9 3 2
tomb [D] gpg: chiffré avec 1 phrase de passe
tomb [D] [GNUPG:] BEGIN_DECRYPTION
tomb [D] [GNUPG:] DECRYPTION_INFO 2 9
tomb [D] [GNUPG:] PLAINTEXT 62 1539149561 
tomb [D] [GNUPG:] PLAINTEXT_LENGTH 219
tomb [D] [GNUPG:] DECRYPTION_OKAY
tomb [D] [GNUPG:] GOODMDC
tomb [D] [GNUPG:] END_DECRYPTION
tomb [D] get_lukskey returns 0
tomb  .  Password OK.
tomb (*) Locking secrets.tomb with secrets.tomb.key
tomb  .  Formatting Luks mapped device.

Something that may be important is that I have a Windows partition on my computer, may it be the cause of the problem ?

**Comment by jaromil** [comment]
Hi! this is very strange. The Win partition shall not be the problem. "Locking" aka LUKS format has to do with the device-mapper and its dm-crypt functionality, but also with the loop mounting system. Some more troubleshooting questions:
- do you have any i/o during the hang? (use iotop)
- is there any related message executing `dmesg` and looking into `/var/log` files?
- can you loop mount and perhaps also LUKS format by hand something and see what happens?

**Comment by jaromil** [comment]
I am really afraid we are looking at GNOME (aka bloatware) interfering with rather delicate basic processes of the operating system. If you need Tomb to work immediately consider switching to another operating system (Devuan.org) which doesn't hides background processes or interfere with what you want to do. If you can wait, I will try to reproduce this problem when I have time, by running tests on an Ubuntu 16 with GNOME/zeitgeist installed.

**Comment by RuyBlast** [comment]
Hi Jaromil,
Thanks a lot for your help and sorry for answering so lately. I just mounted and unmounted a loop device without having any problem following example of man page of losetup. I won't change os for this, I will try another crypto opensource software, but I will consider to change os when I change laptop. Also I think to upgrade to Ubuntu 18 some day, I will try again Tomb and let you know if it works or not on it.
Thank you a lot again !

**Comment by jaromil** [comment]
OK! good luck. I'll keep the issue open for a while since I'd like to investigate further.
