### ISSUE TITLE
Ubuntu wont re-ask password again

### ISSUE THREAD

**Issue by lamdna** [dyne/Tomb#329]
Hello,

I've noticed that if I unlock my tomb volume once, the next time i try (within the same ubuntu session) I don't get the password prompt.

If i reboot the pc then the password prompt appears.

I'm not sure this is the intended default behavior.

**Comment by jaromil** [comment]
What version of Ubuntu?

**Comment by lamdna** [comment]
hey @jaromil 18.04 fresh install. I used tomb v2.5 installed by cloning and "make install"-ing it.

**Comment by lamdna** [comment]
Hey @jaromil were you able to replicate?

I'm not sure if it helps but my default user has autologin.

**Comment by jaromil** [comment]
will take me quite some time to replicate since I don't use Ubuntu on any machine. If anyone can help you to reproduce and investigate, please do post more findings here. thanks!

**Comment by lamdna** [comment]
Hey @jaromil I've noticed that if i issue `gpg-connect-agent reloadagent /bye` after `tomb close all` then I get asked the password again.

If i dont do this, then the password wont get prompted.

launching tomb with -D (when asking for password shows this) : 

```
tomb [D] no password needed, using GPG key
tomb [D] get_lukskey
tomb [D] asking password with tty=/dev/pts/0 lc-ctype=en_US.UTF-8
tomb [D] using pinentry-x11
tomb [W] Attempting key recovery.
tomb [D] Created tempfile: /tmp/zsh/3007514959752110501
tomb [D] gpg: AES256 encrypted data
tomb [D] [GNUPG:] NEED_PASSPHRASE_SYM 9 3 2
tomb [D] [GNUPG:] PINENTRY_LAUNCHED 3377 gnome3 1.1.0 - xterm-256color :0
tomb [D] gpg: encrypted with 1 passphrase
tomb [D] [GNUPG:] BEGIN_DECRYPTION
tomb [D] [GNUPG:] DECRYPTION_COMPLIANCE_MODE 23
tomb [D] [GNUPG:] DECRYPTION_INFO 2 9
tomb [D] [GNUPG:] PLAINTEXT 62 1496676315 
tomb [D] [GNUPG:] DECRYPTION_OKAY
tomb [D] [GNUPG:] GOODMDC
tomb [D] [GNUPG:] END_DECRYPTION
tomb [D] get_lukskey returns 0
tomb [D] lo_preserve on /dev/loop13
```

When it does not prompt anything the log shows this:

```
tomb [D] no password needed, using GPG key
tomb [D] get_lukskey
tomb [D] asking password with tty=/dev/pts/1 lc-ctype=en_US.UTF-8
tomb [D] using pinentry-x11
tomb [W] Attempting key recovery.
tomb [D] Created tempfile: /tmp/zsh/777055712218622842
tomb [D] gpg: AES256 encrypted data
tomb [D] [GNUPG:] NEED_PASSPHRASE_SYM 9 3 2
tomb [D] gpg: encrypted with 1 passphrase
tomb [D] [GNUPG:] BEGIN_DECRYPTION
tomb [D] [GNUPG:] DECRYPTION_COMPLIANCE_MODE 23
tomb [D] [GNUPG:] DECRYPTION_INFO 2 9
tomb [D] [GNUPG:] PLAINTEXT 62 1496676315 
tomb [D] [GNUPG:] DECRYPTION_OKAY
tomb [D] [GNUPG:] GOODMDC
tomb [D] [GNUPG:] END_DECRYPTION
tomb [D] get_lukskey returns 0
tomb [D] lo_preserve on /dev/loop13
```

**Comment by Narrat** [comment]
Either some default from Ubuntu or some config you set in ~/.gnupg/.
Default gpg-agent config doesn't store keys.
Or some session manager?

**Comment by jaromil** [comment]
ACK, I'm glad this is not Tomb's bug and I'm not surprised is a change default settings issue in Ubuntu. Thanks everyone!
