### ISSUE TITLE
 Structure needs cleaning

### ISSUE THREAD

**Issue by strurittrro** [dyne/Tomb#330]
Hi all, 
I don't understand why, but now, when I try to open my tomb I have this problem:

_update_control_file:7: structure needs cleaning: /media/XXXXXX/.uid
chown: cannot access '/media/XXXXXX/.uid': Structure needs cleaning
_update_control_file:7: structure needs cleaning: /media/XXXXXX/.tty
chown: cannot access '/media/XXXXXX/.tty': Structure needs cleaning
_update_control_file:7: structure needs cleaning: /media/XXXXXX/.host
chown: cannot access '/media/XXXXXX/.host': Structure needs cleaning
_update_control_file:7: structure needs cleaning: /media/XXXXXX/.last
chown: cannot access '/media/XXXXXX/.last': Structure needs cleaning
chown: changing ownership of '/media/XXXXXX/.uid': Structure needs cleaning
chown: changing ownership of '/media/XXXXXX/.host': Structure needs cleaning
chown: changing ownership of '/media/XXXXXX/.last': Structure needs cleaning
chown: changing ownership of '/media/XXXXXX/.tty': Structure needs cleaning
chown: changing ownership of '/media/XXXXXX/last_database_septmber_2018.kdbx': Structure needs cleaning

and I am unable to open some files...
how I can resolve?
thanks in advance

**Comment by jaromil** [comment]
have you tried searching for the error and chown? your storage support may be damaged.
