### ISSUE TITLE
"Failure mounting the encrypted file" after failed resize

### ISSUE THREAD

**Issue by ghost** [dyne/Tomb#333]
A tomb file would become impossible to mount in certain conditions after a failed resize. Here's how to reproduce the issue:

1. Create a tomb as normal (`dig`, `forge` a key, then `lock` the tomb with that key).
2. Use `tomb resize` on the tomb file.
3. Insert a wrong password 3 times, or at least until it fails.

Now, the tomb file is resized evenutally however it will becomes umountable and returns "Failure mounting the encrypted file".

I'd suggest to fix by asking for the passphrase before actually resizing it.

**Comment by jaromil** [comment]
fixed, many thanks!
