### ISSUE TITLE
Misaligned usage message lines

### ISSUE THREAD

**Issue by jcrd** [dyne/Tomb#335]
While this is only a cosmetic issue, I find the usage message a bit difficult to read due to the misaligned lines.

![image](https://user-images.githubusercontent.com/44040597/48972301-a5520d00-efe4-11e8-909a-98f10c703553.png)

I could not figure out how to align them using tabs. Would it be acceptable to align them manually with spaces? If so, I'll create a PR.

**Comment by jaromil** [comment]
yes I think spaces is the best solution. I don't remember if zsh has some fancy builtin for that, but anything else would be bloat.
