### ISSUE TITLE
Do you have a logo?

### ISSUE THREAD

**Issue by pawamoy** [dyne/Tomb#339]
Preferably SVG? For VectorLogoZone: https://github.com/VectorLogoZone/vectorlogozone/issues/26

**Comment by jaromil** [comment]
it is the small pixelated skull called "monmort.png" made +10years ago by the graffiti artist Mon Mort from Barcelona (some of his murales are still visible in the city). No problem in making it pixelated on resize, it is meant to.

**Comment by jaromil** [comment]
To be precise, is this one https://github.com/dyne/Tomb/blob/8d698ad46aa11d45880d2bc00f2d631608fe46a6/extras/gtk-tray/monmort.xpm

**Comment by pawamoy** [comment]
Thanks, I'll relay this info when I get some feedback from VLZ.
