### ISSUE TITLE
GPG error related to trust is silently eaten

### ISSUE THREAD

**Issue by sowbug** [dyne/Tomb#340]
```
$ tomb dig -s 16 test-tomb.tomb
$ tomb forge -g -r 01234567 test-tomb.tomb -k test-tomb.key
[snip]
tomb (*) Using GnuPG key(s) to encrypt your key: test-tomb.key
[snip]
tomb [W] is_valid_key() called without an argument.
tomb [W] The key does not seem to be valid.
$ ls -l
-rw------- 1 miket miket        0 Jan 26 10:31 test-tomb.key
-rw------- 1 miket miket 16777216 Jan 26 10:29 test-tomb.tomb
$ gpg --edit-key 01234567
[configure GnuPG to trust the key]
$ rm test-tomb.key
$ tomb forge -g -r 01234567 -k test-tomb.key test-tomb.tomb 
[snip]
tomb  .  Key is valid.
tomb  .  Done forging test-tomb.key
tomb (*) Your key is ready:
-rw------- 1 miket miket 1016 Jan 26 10:41 test-tomb.key
```

This is a very condensed history of a debugging session. If Tomb noticed that the underlying GnuPG commands failed (or I suspect asked an unexpected question about whether the user was sure about the recipient's public key), and echoed that information to console, then it would have been easier for the end user to understand why this was failing.

**Comment by jaromil** [comment]
Interactivity of gnupg is a problem, since Tomb is explicitly designed to not be interactive. We may add a check on trust level of key used by -g already by tomb and make it refuse to use it unless trusted.

**Comment by jaromil** [comment]
many thanks for sorting this out so well
