### ISSUE TITLE
POSIX Shell Migration from ZSH

### ISSUE THREAD

**Issue by MyNameIsCosmo** [dyne/Tomb#341]
I would like to migrate away ZSH and use `#!/bin/sh` for Tomb.

Being new to this project (and having to go through 3k+ lines of shell code, not including tests, etc), I'd like to get some feedback first before continuing down this path.

Is there any hard requirement of why Tomb is written for ZSH? 
If not, would it be accepted if I started submitting patches to change ZSH-specific features to POSIX-compliant code for users who prefer to use a shell other than ZSH (i.e. `#!/bin/zsh -> /bin/sh`)
From my understanding, ZSH could still be used to run `tomb`.

Having a fork or a new project similar to Tomb seems redundant and a waste of effort, considering that Tomb is a great project.

Any thoughts, concerns, and questions are appreciated.

**Comment by jaromil** [comment]
There are several requirements that perhaps bash could absolve but sh definitely not.
I'm not really looking forward to change shell interpreter for Tomb, so I wouldn't merge such changes.

**Comment by MyNameIsCosmo** [comment]
Noted.
Thanks!
