### ISSUE TITLE
Can't forge a key

### ISSUE THREAD

**Issue by ice-ice** [dyne/Tomb#349]
![QQ截图20190513161327](https://user-images.githubusercontent.com/3909351/57609910-63248400-75a2-11e9-896d-83b5c33e0200.png)

It's too slow to generate

version: ubuntu 18  + tomb2.5

**Comment by ice-ice** [comment]
no error 

and 

Executed successfully
`sudo apt install gnupg zsh cryptsetup pinentry-curses steghide`

**Comment by ice-ice** [comment]
I've solved the problem

`sudo apt-get install rng-tools`
`rngd -r /dev/urandom`

**Comment by Narrat** [comment]
As the whole operation depends on the available pool, it can be slow to generate a key. And solutions are mentioned for those cases.
So imo this can be closed.

**Comment by ice-ice** [comment]
Actually I think you should add it to the document.

There must be a lot of people who have this problem

**Comment by jaromil** [comment]
This is puzzling, since we use the non-blocking `/dev/urandom`:
```
dd if=/dev/urandom bs=1048576 count=$tombsize
```
basically there shouldn't be much waiting involved.

**Comment by ice-ice** [comment]
version: ubuntu 18 + tomb2.5

ubuntu 18
It's a new system
It's never been used

You can re-install a ubuntu18 system and give it a try.

Linux version 4.18.0-20-generic (buildd@lcy01-amd64-020) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019

**Comment by Narrat** [comment]
For the tomb, `dev/urandom` is used, but afaik the key gen relies on `dev/random`

**Comment by ice-ice** [comment]
> For the tomb, `dev/urandom` is used, but afaik the key gen relies on `dev/random`

For now, the problem is real.

**Comment by Narrat** [comment]
But it is system/user specific. rng-tools or haveged (an alternative) aren't really necessary. Especially if there is a hardware random number generator like the Pi offers.
Which would be interesting to see:
`# cat /proc/sys/kernel/random/entropy_avail`
and maybe the `pool_size`
Fresh after booting the system, some time later and while trying to generate a key.

**Comment by jaromil** [comment]
After much research and listening to experts I realise that the need to use the blocking `/dev/random` source is a thing of the past and mostly a urban legend now, so I'll switch to `/dev/urandom` for the next release, this is something I wanted to do for a while now.

**Comment by jaromil** [comment]
See https://www.2uo.de/myths-about-urandom/ (thanks @danielinux for the link)

**Comment by Narrat** [comment]
Interesting read. Although I kinda miss sources. Especially if one can read at other places something like in the [Arch Wiki](https://wiki.archlinux.org/index.php/Random_number_generation#/dev/urandom)
> Myths about urandom - highly informative but (unfortunately) also containing fallacies, and (...)

But again, without mentioning any sources or even hint at those fallacies (if there are any) >.> ugh...

**Comment by jaromil** [comment]
Of course there is still possibility to choose your own method, its just a change of default.

**Comment by Narrat** [comment]
Sure. My comment was more of a general rant. No particular feeling for either solution. But as I have no real insight into the topic cryptography, talks/posts without sources kinda feel like "Trust me" posts..
