### ISSUE TITLE
gtk-tray issue no gtk file 

### ISSUE THREAD

**Issue by CoderK19** [dyne/Tomb#351]
This may be an issue with my lack of Linux experience, but I have ensured that I have both libnotify installed (version: 0.7.7-3) and gtk+-2.0 dev (version: 2.24.32-1ubuntu1) installed on my Ubuntu 18.04 Bionic Beaver. however, I am not able to make tomb-gtk-tray from extras/gtk-tray. It gives me the error from the picture. I can not figure out how to resolve this after spending a couple hours trying. Please help as I like this product and want to you it to the full capacity.

![errormsg](https://user-images.githubusercontent.com/50905933/58159760-07a56680-7c32-11e9-9be8-b03c0c7855ac.png)
 
![libraries](https://user-images.githubusercontent.com/50905933/58160161-c5c8f000-7c32-11e9-9b2b-28c7a4ae31fb.png)

**Comment by Narrat** [comment]
It should be mentioned, that the extra `gtk-tray` is unmaintained. Not sure if it still is working as intended.

You propably meant the package name `libgtk2.0-dev`?
Nevertheless, you could execute the pkg-config directly and look what it reports back
``` sh
$ pkg-config --cflags --libs gtk+-2.0
-I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/libffi-3.2.1/include -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/atk-1.0 -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype
```
Should be the result. If not, please check of there are files at `/usr/include/gtk-2.0/`. Especially if there is a folder `gtk` containing said `gtk.h`.

**Comment by jaromil** [comment]
Well, I wrote the gtk-tray, but don't use it anymore, however it should work on systems enabling the gtk2/3 model for trays. Ubuntu is a shifting target and has changed its tray support several times, AFAIK is not compatible with the freedesktop specification since two or three major versions?
