### ISSUE TITLE
Invalid default cipher "aes-xts-plain64:sha256"

### ISSUE THREAD

**Issue by 68420948** [dyne/Tomb#352]
Hi,

while packaging tomb for Debian I found this issue:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=930782

(Text copied)
The default cipher is not accepted by cryptsetup any more.

Locking a freshly digged tomb by

    $ tomb lock -k x.key x.tomb

fails with

    [...]
    tomb [W] cryptsetup luksFormat returned an error.
    tomb [E] Operation aborted.

According to https://gitlab.com/cryptsetup/cryptsetup/wikis/DMCrypt the default
cipher "aes-xts-plain64:sha256" is not valid. ":sha256" only goes with "aes-
cbc-essiv:sha256". The valid cipher would be "aes-xts-plain64".

Locking the tomb specifying the valid cipher on the command line works

    $ tomb lock -k x.key -o aes-xts-plain64 x.tomb

    [...]
    tomb  .  Done locking x using Luks dm-crypt aes-xts-plain64
    tomb (*) Your tomb is ready in x.tomb and secured with key x.key

"aes-xts-plain64:sha256" should be corrected to "aes-xts-plain64" in
/usr/bin/tomb and the manpage.

Please consider this patch:
https://salsa.debian.org/pkg-security-team/tomb/blob/debian/master/debian/patches/fix-default-cipher.patch

Cheers,
Sven

**Comment by Narrat** [comment]
Thanks for the note. This issue got fixed by https://github.com/dyne/Tomb/pull/348
But as there is no new release currently... :)

**Comment by jaromil** [comment]
its released in 2.6!

**Comment by Narrat** [comment]
Oh, didn't check the homepage. Indeed a 2.6 release was done :)
Missed it, because this repo doesn't contain the tag, so this tags needs to be pushed?

**Comment by jaromil** [comment]
forgot to do that! done, thanks for reminder :^)
