### ISSUE TITLE
Parse Error in tomb script file

### ISSUE THREAD

**Issue by wsellars-bw** [dyne/Tomb#357]
/usr/local/bin/tomb:1444: parse error near `]]'

All dependencies installed and up to date - Centos 7

**Comment by jaromil** [comment]
hi! what is around line 1444 of your tomb script? what version of tomb and zsh?

**Comment by wsellars** [comment]
missed this notification, sorry. Latest ZSH on CentOS 7 EHEL and Tomb 2.6
off the top of my head. Line 1444 is ```if [[ $sphx_host_tmp ]] || [[
$sphx_user_tmp ]]; then```

*Walter Sellars*  •  Database Administrator Intern

900 Main Campus Drive, Suite 500, Raleigh, NC 27606

m: 305-299-9800
e: wsellars@bandwidth.com

**Comment by jaromil** [comment]
Thanks! I see it may be the incorrect use of tests to check if variables are filled.

**Comment by wsellars** [comment]
So is there a solution I can implement for this, or perhaps an older version that doesn't use these checks? I'd really like to use tomb because it perfectly fits my needs for a project, but I'm really not sure how to progress with it if it won't run

**Comment by saneax** [comment]
I too am hitting the same issue -

**Comment by jaromil** [comment]
should be fixed by the commit above, can you please try latest git master and let us know? thanks!

**Comment by jaromil** [comment]
@wsellars-bw ACK releasing soon, thanks
