### ISSUE TITLE
tomb-kdb-pbkdf2 fails with 'Error allocating memory' on non-Intel/AMD architectures

### ISSUE THREAD

**Issue by 68420948** [dyne/Tomb#360]
Automatic package tests at Ubuntu [1] failed for architectures arm64, armhf, ppc64el and s390x.

After some digging I found the root cause in extras/kdf-keys/pbkdf2.c at line 143,144:
```
    char c = getchar();
    while (c != EOF) {
```
getchar() returns an int, which is convert to a char which in turn is compared to an int. The result of this comparison is undefined as the char type has no defined sign, while int is signed.

In case getchar() returns an EOF (= -1 = 0xffffffff) this is converted to a char represented by 0xff.

Code for amd64 and i386 seem to  convert 0xff back to 0xfffffff, so the EOF is recognized with the while test.
Code for armhf and ppc64el (I only tested these) seem to convert 0xff back to 0x000000ff, so the EOF is never recognized, the routine allocates more and more memory to store the 0xff characters and ends up consuming all available memory, thus the error message.

I fixed this for Debian with a patch [2]. Please consider to re-integrate this change into your code.

[1] https://autopkgtest.ubuntu.com/packages/tomb
[2] https://salsa.debian.org/pkg-security-team/tomb/blob/debian/master/debian/patches/fix-unrecognized-eof.patch

In addition this bug revealed a different flaw in the tomb shell script, function forge_key().

```
[...]
    # this does a check on the file header
    is_valid_key $TOMBKEY || {
        _warning "The key does not seem to be valid."
        _warning "Dumping contents to screen:"
        print "${mapfile[$TOMBKEY]}"
        _warning "--"
        _sudo umount ${keytmp}
        rm -r $keytmp
        _failure "Operation aborted."
    }
[...]
```
$keytmp is undefined, so _sudo umount and rm -r fail. From my understanding of the code $keytmp should be replaced by  $TOMBKEYFILE. I didn't prepare a patch for this issue. 

Cheers,
Sven

**Comment by jaromil** [comment]
Thanks Sven! this is a useful contribution, will merge upstream.
