### ISSUE TITLE
Tomb for individual files

### ISSUE THREAD

**Issue by pawamoy** [dyne/Tomb#363]
Do you think it's possible and not too hard to write a wrapper that uses Tomb to encrypt individual files, and mount them on the same path when opening/decrypting them?

Or do you know any other software solution to achieve that?

With such functionality, it would then be possible to have some underlying file-system feature that transparently decrypt/mount these encrypted files when a program tries to read/write them. No more manual decryption, resizing, secure templating or loading tokens in environment variable from encrypted files, it would all be transparent and ask for the key password each time the file is accessed :slightly_smiling_face:

**Comment by jaromil** [comment]
I believe it is easily done by creating a folder with a single file inside.
To automate this I'd rather create a wrapper to tomb that create the dir, moves the file inside, saves the location in .bind_hooks and creates the tomb. There will be issues to be sorted about the directory location then, but for the way `mount bind` works there will always be issues.
