### ISSUE TITLE
`_get_home` returns shell path instead

### ISSUE THREAD

**Issue by OttoAllmendinger** [dyne/Tomb#365]
the line for my user is

```
otto:x:1000:1000::/home/otto:/usr/bin/zsh
```

calling tomb prints this

```
tomb [D] Identified caller: otto (1000:1000)
tomb [D] Updating HOME to match user's: /usr/bin/zsh (was /home/otto)
```

**Comment by jaromil** [comment]
hi! what version of Tomb and Zsh are you using?
```
print ${"$(getent passwd otto)"[(ws@:@)6]}
```
what is the output of the command above if you run it in Zsh?

what you report is very strange, as the home is 6th position also according to your line

**Comment by OttoAllmendinger** [comment]
```
» pacman -Q tomb zsh
tomb-git 2.6.r15.gca708b4-1
zsh 5.7.1-1

» print ${"$(getent passwd otto)"[(ws@:@)6]}

/usr/bin/zsh
```

I think it is because one of the columns is empty:

```
» print ${"$(echo 1:2:3:4:5:6:7)"[(ws@:@)6]}

6

otto@otcx1 » ~ # (note extra colon)
» print ${"$(echo 1:2:3:4::5:6:7)"[(ws@:@)6]}

6
```

**Comment by jaromil** [comment]
dear Otto, well spotted! thanks. Using awk then should fix it (is already a dependency in Tomb)
```sh
echo 1:2:3:4::5:6:7 | awk -F: '{print $6}'
-> 5
```
I'll fix it soon, else feel free to open a PR yourself.

BTW using tomb's git version is not recommended at all, I hope Arch has at least an option to install the stable version.

**Comment by OttoAllmendinger** [comment]
I'll leave the awk magic to you ;)

**Comment by Narrat** [comment]
> BTW using tomb's git version is not recommended at all, I hope Arch has at least an option to install the stable version.

The option exists, yes
