### ISSUE TITLE
Invalid cipher still mentioned in manpage and Tomb script

### ISSUE THREAD

**Issue by 68420948** [dyne/Tomb#370]
The invalid cipher aes-xts-plain64:sha256 is still to be found in the manpage as well as in a comment in the Tomb script.
I suggest you apply this patch https://salsa.debian.org/pkg-security-team/tomb/blob/debian/master/debian/patches/fix-default-cipher.patch
Cheers,
Sven

**Comment by jaromil** [comment]
Fixed in e9fd1a1
