### ISSUE TITLE
Data offset is outside of currently available data device

### ISSUE THREAD

**Issue by s-kaczmarek** [dyne/Tomb#374]
Hi, while performing step of locking tomb, I get error:

> user@user:~/tomb-test$ tomb lock secret.tomb -k secret.tomb.key
> tomb  .  Commanded to lock tomb secret.tomb
> tomb  .  Checking if the tomb is empty (we never step on somebody else's bones).
> tomb  .  Fine, this tomb seems empty.
> tomb  .  Key is valid.
> tomb  .  Locking using cipher: aes-xts-plain64:sha256
> tomb  .  A password is required to use key secret.tomb.key
> tomb  .  Password OK.
> tomb (*) Locking secret.tomb with secret.tomb.key
> tomb  .  Formatting Luks mapped device.
> WARNING: Data offset is outside of currently available data device.
> Device wipe error, offset 10485760.
> Cannot wipe header on device /dev/loop6.
> tomb [W] cryptsetup luksFormat returned an error.
> tomb [E] Operation aborted.

Could you please tell me, what is wrong with that?

**Comment by Narrat** [comment]
What does `tomb -v` print? Size of the tomb?

**Comment by jaromil** [comment]
lack of info
