### ISSUE TITLE
Rpi no access to tomb folders after apt update

### ISSUE THREAD

**Issue by peterthomsonou** [dyne/Tomb#383]
I am working with a network of Rpi computers. The problem appeared on an RPi 4 running current Raspian.
I started this morning with apt update and upgrade. When I attempted to open several tomb folders, each one told me that the password was not recognised.
My Ubuntu desktop could not open these folders.

I could create and lock and reopen new folders on the RPi4.
I could open tomb folders on the RPi4 created many years ago on a Ubuntu desktop.

What I did notice was that prior to the apt update the request for password appears as part of the terminal window. After the update the request for password appears as a separate window. But the terminal version hasn't changed. Using Xterm and UXterm made no difference.

As I have on the network a Pi3B set up with the same current Raspian, I installed Tomb and its dependencies on that, copied over the encrypted folder and key - and tomb opened it without a problem. So one day of panic over ( I worked back through all the backup generations of encrypted tomb folders and none would open!)

But it would be useful to know what caused the problem, and how to get out of it if you cannot go back to the original setup.
Thanks
(I will cross post to a Rpi forum as well)

**Comment by Narrat** [comment]
It would be helpful if you could provide debug outputs and the setup of the working Pi3B and the non-working Pi4.
Infos regarding the setup via `tomb -v` and debug output with `-D` applied to the tomb commands.

**Comment by peterthomsonou** [comment]
Output file attached.
Note that on neither system does decryption work to completion when -D option applied.
OS: Raspian
[tomb not opening.txt](https://github.com/dyne/Tomb/files/5266201/tomb.not.opening.txt)

**Comment by jaromil** [comment]
@peterthomsonou there is an evident difference between pinentry-curses working, but that has been substituted to pinentry-gnome3 on the rpi4 which also explains the dialogue change. maybe pinentry-gnome3 has bugs in string processing, while ncurses one works?

**Comment by peterthomsonou** [comment]
After further checking: tombs / tomb passwords created on the Rpi3 and 4 using pinentry-curses are not compatible with tombs created on a ubuntu desktop computer, and are not compatible with Rpi4 using pinentry-gnome3

Tombs created on ubuntu desktop computer and Rpi4 using pinentry-gnome3 are compatible when moved between the two. I think that suggests the bug was in pinentry curses  on Raspian and is corrected by the use of pinentry-gnome3.

Would you agree with that?

I don't think there will be any way of updating existing tombs on Raspbian other than copying out the data after unlocking with pinentry-curses, and then creating new tombs with  pinentry-gnome3

**Comment by jaromil** [comment]
To prove your hypothesis I think should be enough to use the two different pinentry programs, print out their output and compare it.

**Comment by jaromil** [comment]
It seems we have found the reason of this in #385 and it is fixed now. Stable release coming soon.

**Comment by jaromil** [comment]
supposedly fixed, please reopen if still occurring.
