### ISSUE TITLE
Avoid mounting same tomb twice on a user specified directory

### ISSUE THREAD

**Issue by shaform** [dyne/Tomb#387]
Tomb 2.7 is currently allowing users to mount the same tomb multiple times if users provide a target directory:

```
$ tomb dig -s 100 secret.tomb
$ tomb forge secret.tomb.key
$ tomb lock secret.tomb -k secret.tomb.key
$ mkdir -p target_dir
$ tomb open secret.tomb target_dir -k secret.tomb.key
$ tomb open secret.tomb target_dir -k secret.tomb.key
$ tomb open secret.tomb target_dir -k secret.tomb.key
```

However, doing so result in lost of data as mentioned in roddhjav/pass-tomb#27 or #326.

It would be preferable to avoid this behavior.

**Comment by jaromil** [comment]
Thanks for the reminder, you are welcome to review the PR #389
