### ISSUE TITLE
libsphinx test build broken

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#388]
Seems trivial, missing `pkgconf` from docker file:
https://travis-ci.org/github/dyne/Tomb/jobs/742943357#L949

Anyone can help here? @roddhjav ?

**Comment by jaromil** [comment]
Omitting libsphinx tests fixed the issue: https://travis-ci.org/github/dyne/Tomb/builds/743513885

I guess we can consider this minor, curious to know if anyone is using the [sphinx](https://github.com/stef/libsphinx) extra.

**Comment by roddhjav** [comment]
Adding `pkgconf` is not enough to fix the issue. I have never use the sphinx extra. So I don't know how to fix this.

**Comment by heat-wave** [comment]
I wasn't actively using sphinx and things got out of sync. Briefly:
- **libsphinx** requires **libsodium-1.0.18** which is not available in default repo (but can be built from source)
- **pwdsphinx** somewhat silently changed config requirements and now doesn't work without SSL certificate (we can generate it for testing purposes)
- **oracle** (server side of sphinx) appears to be working correctly after including the config, but **sphinx** (client side) has more issues: on latest version 0.5 the arguments aren't parsed properly; on 0.3.1 they are, but most operations return `Aborted (core dumped)`
I'll try to get it working this week if no one minds. Also, building libsphinx from source takes time, so maybe it's better to add a repo that has the right version if it's feasible.

**Comment by jaromil** [comment]
Given the complexity of the implementation (the presence of a daemon) it would be lovely to have sphinx and oracle packaged in Debian... I wonder if there is any progress or hope on that @stef ? should we open a RFP?

**Comment by stef** [comment]
hey, i'm rewriting the sever in zig here: https://github.com/stef/zphinx-zerver/ and the python client is more or less ready. however the websphinx interface that serves the webextenstions for chrome and firefox is currently broken, am at this moment working on fixing it. if you don't care about the webext inteface the rest could be packaged.

**Comment by stef** [comment]
some more info: we reworked the protocol to have stronger security properties, hence backward incompatibility. the most important now is the webextension interface to fix. if there is anything else that does not work pls open tickets at either pwdsphinx or at zphinx-zerver repos.

**Comment by heat-wave** [comment]
Splendid, I'll be happy to update the code/tests/dockerfile once the updated client/package is available.

**Comment by stef** [comment]
> * **libsphinx** requires **libsodium-1.0.18** which is not available in default repo (but can be built from source)

oh? why is the latest libsodium not available in the default repo? it's quite old now...

> * **pwdsphinx** somewhat silently changed config requirements and now doesn't work without SSL certificate (we can generate it for testing purposes)

yeah, well, the client actually does not need a certificate if the server has a cert signed by a CA in the certstore. the code requiring this cert is actually some development artifact. i'll remove this in the next release. i added an issue for this https://github.com/stef/pwdsphinx/issues/12

> 
> * **oracle** (server side of sphinx) appears to be working correctly after including the config, but **sphinx** (client side) has more issues: on latest version 0.5 the arguments aren't parsed properly; on 0.3.1 they are, but most operations return `Aborted (core dumped)`

was this what you reported in https://github.com/stef/pwdsphinx/issues/11 or is this coredump something else?

>   I'll try to get it working this week if no one minds. Also, building libsphinx from source takes time, so maybe it's better to add a repo that has the right version if it's feasible.

why does libsphinx builds take time? it should be only like 2-3 c files that need compilation now since we dumped libdecaf and went for libsodium...

**Comment by stef** [comment]
actually i fixed also stef/pwdsphinx#12 just now. hope it works for you guys.

**Comment by heat-wave** [comment]
> oh? why is the latest libsodium not available in the default repo? it's quite old now...

Well at least that's what I'm getting:

> # apt show libsodium23
> Package: libsodium23
> Version: 1.0.17-1
> APT-Sources: http://deb.devuan.org/merged beowulf/main amd64 Packages

> was this what you reported in [stef/pwdsphinx#11](https://github.com/stef/pwdsphinx/issues/11) or is this coredump something else?

Coredump happened when I specified version 0.3.1 in pip3 and tried getting around that entrypoint issue. I'll reproduce it if it's important but since the newer version works fine after amending the entrypoint, maybe it's less urgent.

> why does libsphinx builds take time? it should be only like 2-3 c files that need compilation now since we dumped libdecaf and went for libsodium...

Apologies, I meant building libsodium :facepalm: libsphinx has no such issue indeed

**Comment by stef** [comment]
> > oh? why is the latest libsodium not available in the default repo? it's quite old now...
> 
> Well at least that's what I'm getting:
> 
> > apt show libsodium23
> > Package: libsodium23
> > Version: 1.0.17-1
> > APT-Sources: http://deb.devuan.org/merged beowulf/main amd64 Packages

ah, yeah, i guess testing/stable are not so quick in updating packages...

> > was this what you reported in [stef/pwdsphinx#11](https://github.com/stef/pwdsphinx/issues/11) or is this coredump something else?
> 
> Coredump happened when I specified version 0.3.1 in pip3 and tried getting around that entrypoint issue. I'll reproduce it if it's important but since the newer version works fine after amending the entrypoint, maybe it's less urgent.

ah, i guess that coredump is because wrong parameters passed to the c library... ok, ignore the coredump.

> 
> > why does libsphinx builds take time? it should be only like 2-3 c files that need compilation now since we dumped libdecaf and went for libsodium...
> 
> Apologies, I meant building libsodium facepalm libsphinx has no such issue indeed

hehe. :)
thanks!

**Comment by stef** [comment]
with the latest commits for websphinx i can confirm the webextensions in chrom{e|ium} work again, i expect the firefox also working again.

**Comment by heat-wave** [comment]
#408 gets the test build working again, along with some overdue updates to handling pwdsphinx error response. Feel free to check it out whenever it's convenient

**Comment by jaromil** [comment]
Closing this as it seems solved, thanks!!
