### ISSUE TITLE
tomb forge : fails on ask_password:59: pinentry_assuan_getpassgetpasspass

### ISSUE THREAD

**Issue by zzgab** [dyne/Tomb#395]
Hi,

Great tool, great work!

# Problem

With Tomb **2.8** on **WSL**+Ubuntu 18.04 :

command ` tomb forge -k tomb.key` fails with error: 
`ask_password:59: command not found: pinentry_assuan_getpassgetpasspass`

# Output

~~~
~ tomb forge -k tomb.key
tomb  .  Commanded to forge key tomb.key with cipher algorithm AES256
tomb [W] This operation takes time. Keep using this computer on other tasks.
tomb [W] Once done you will be asked to choose a password for your tomb.
tomb [W] To make it faster you can move the mouse around.
tomb [W] If you are on a server, you can use an Entropy Generation Daemon.
512+0 records in
512+0 records out
512 bytes copied, 0.0019976 s, 256 kB/s
tomb (*) Choose the password of your key: tomb.key
tomb  .  (You can also change it later using 'tomb passwd'.)
ask_password:59: command not found: pinentry_assuan_getpassgetpasspass
tomb [E] User aborted.
~~~

# Additional info

All the [listed dependencies](https://github.com/dyne/Tomb/blob/master/INSTALL.md#install-required-tools) are correctly installed.

On same platform, same conditions, same command, Tomb **2.7** works.

Please advise?
Thanks!

**Comment by jaromil** [comment]
This was a typo and recently fixed by @Narrat, we are issuing a new stable release this week. Thanks for the report!

**Comment by zzgab** [comment]
🙏
