### ISSUE TITLE
`file` should be among dependencies

### ISSUE THREAD

**Issue by madepolli** [dyne/Tomb#396]
I am on an instance of ubuntu-based armbian, and it seems it does not have package `file` installed by default.  When forging the key I got (just showing the relevant part here):
~~~
...
tomb  .  (You can also change it later using 'tomb passwd'.)
is_valid_key:21: command not found: file
tomb  .  Key is valid.
...
~~~
Later I just did `sudo apt install file` so that hopefully nothing brakes for me later on.

**Comment by jaromil** [comment]
Hi! thanks, you are right. Also you make me think if we can in some way get rid of the dependency, which is used just two times to analyse if a file is a JPG in `is_valid_key()` and if a file is a LUKS volume in `is_valid_tomb()`. Not urgent, food for later thoughts.
