### ISSUE TITLE
Wrong help message displayed with --help

### ISSUE THREAD

**Issue by iandstanley** [dyne/Tomb#397]
When you use the --help option to remind yourself about locking the tomb
tomb tells the user to use **tomb lock file.tomb file.tomb.key** 
missing out the need to use the **-k**:

**$ tomb lock --help**
tomb [W] No tomb specified for locking.
**tomb [W] Usage: tomb lock file.tomb file.tomb.key**

**$ tomb lock myarchive.tomb myarchive.tomb.key** 
tomb  .  Commanded to lock tomb myarchive.tomb
tomb  .  Checking if the tomb is empty (we never step on somebody else's bones).
tomb  .  Fine, this tomb seems empty.
**tomb [E] This operation requires a key file to be specified using the -k option.**

**$ tomb lock myarchive.tomb -k myarchive.tomb.key**

**Comment by jaromil** [comment]
Hi!
Latest version line 1979:
```sh
	[[ -n $tombpath ]] || {
		_warning "No tomb specified for locking."
		_warning "Usage: tomb lock file.tomb -k file.tomb.key"
		return 1
	}
```
you must be using an older version of Tomb
