### ISSUE TITLE
Getting /usr/local/bin/tomb:393: parse error near `]]'

### ISSUE THREAD

**Issue by rajashekar** [dyne/Tomb#398]
**Getting error when running tomb.** 
➜  ~ tomb -h
/usr/local/bin/tomb:393: parse error near `]]'

Installed through Tomb-**2.8.1**.tar.gz

**Below are my environment details -** 
➜  ~ more /etc/centos-release
CentOS Linux release 7.3.1611 (Core)

➜  ~ zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)

➜  ~ gpg --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ?, ?, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

➜  ~ sudo yum install pinentry
Package pinentry-0.8.1-17.el7.x86_64 already installed and latest version

➜  ~ sudo yum install cryptsetup
Package cryptsetup-2.0.3-6.el7.x86_64 already installed and latest version

**Comment by rajashekar** [comment]
I am not seeing above issue with Tomb 2.7.

**Comment by jaromil** [comment]
@rajashekar ACK. I believe this is an issue with older versions of Zsh, the main difference between tomb 2.7 and tomb 2.8.x is that I have started using the notations [[ $VAR ]] to check if an environment variable exists, seeing that it passed test but not realizing it can generate a regression.

**Comment by rajashekar** [comment]
@jaromil - I tried 2.8.1 in latest Ubuntu(tried in both physical box and Docker), its working fine. As you mentioned, its only issue with old versions of ZSH. Either update the docs mentioning 2.8.x will support only from certain version of ZSH or fix 2.8.x to support older versions of ZSH.

**Comment by jaromil** [comment]
@rajashekar thanks for the report and confirmation Rajashekar! I will work over this weekend to make a fix, it makes no sense for us to create regressions within the v2.x course
