### ISSUE TITLE
Failed to load module "xapp-gtk3-module"

### ISSUE THREAD

**Issue by zhogano** [dyne/Tomb#405]
I am using manjaro linux 20.2. After the major update (kernel was also updated to 5.10.2-2) on 31th December 2020, I started to get this message while mounting the tomb volume:

`Gtk-Message: 12:04:54.521: Failed to load module "xapp-gtk3-module"`

Tomb version is:   2.8.1
Other than this warning, everything seems to work fine. Is this something I should worry about? What does it mean?

More detailed output is:
```
tomb  .  Commanded to open tomb ...........
tomb  .  Valid tomb file found: ............
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /run/media/..........
tomb (*) Opening backup2 on /run/media/.............
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "twofish" mode "xts-plain64" hash "sha512"
tomb  .  A password is required to use key .....................
Gtk-Message: 12:04:54.521: Failed to load module "xapp-gtk3-module"
Gtk-Message: 12:04:54.522: Failed to load module "xapp-gtk3-module"
tomb  .  Password OK.
tomb (*) Success unlocking tomb .........
tomb  .  Checking filesystem via /dev/loop7
fsck from util-linux 2.36.1
..........: clean, 8068/2564096 files, 6504967/10239488 blocks
tomb (*) Success opening ............ on /run/media/.................
tomb  .  Last visit by ......(1000) from /dev/pts/1 on..........
tomb  .  on date Fri 01 Jan 2021 10:55:50 AM +03
```

**Comment by jaromil** [comment]
@zhogano I think there is nothing to worry, seems something related to pinentry

**Comment by zhogano** [comment]
Thank you @jaromil.  You are right, from the terminal, when I type `pinentry` I again get "Failed to load module "xapp-gtk3-module". So it seems something is wrong on my computer.
Sorry for my ignorance, I just want to ask you:
I found from the manpage of pinentry: "pinentry-gtk-2 is a program that allows for secure entry of PINs or pass phrases. That means it tries to take care that the entered information is not swapped to disk or temporarily stored anywhere.". So if there is a failure in loading the module, isn't it something for me to worry about?

By the way thank you for this great software "tomb" !!

**Comment by jaromil** [comment]
I wouldn't worry to me seems the message indicates a failure on the `dlopen()` call to a gtk3 plugin, which wouldn't allow an eavesdropper to intercept the password typed. Good luck!
