### ISSUE TITLE
tomb [E] Tomb file already in use: secret.tomb

### ISSUE THREAD

**Issue by z-empyrean** [dyne/Tomb#407]
I have installed version Tomb 2.9.0 on devuan beowulf stable, not from the repos i have used the release file from github.

everything seems to work thus far except when locking the tomb.

steps taken from man page.

```
                   tomb dig -s 128 secret.tomb

                   tomb forge secret.tomb.key

                   tomb lock secret.tomb -k secret.tomb.key

                   tomb open secret.tomb -k secret.tomb.key
```

when i try to lock the tomb after opening it says...

`tomb [E] Tomb file already in use: secret.tomb`

lsblk shows:

```
NAME                                                                                 MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0                                                                                  7:0    0   128M  0 loop
└─tomb.secret.fdebb113c5fccd406c677a513f86ca10c7cfcecb550d1d3d3f6aab57cc2999d3.loop0 254:1    0   126M  0 crypt /media/secret
```
i can manally unmount using sudo umount /media/secret and then sudo cryptsetup close tomb.secret.XXXX

But shouldn't tomb lock do these functions?

Kind regards

**Comment by jaromil** [comment]
Hi, we have tests that verify well this basic condition, I also have tried by hand but could not reproduce. Perhaps you have something strange in your setup? please paste the output of `tomb -v`.

Not sure if its a typo, however in your description you mention "lock the tomb after opening" but that's not the sequence, you should lock once the tomb (upon creation) and then open/close when you like.

**Comment by z-empyrean** [comment]
hi, im sorry i should have read the manual more in depth. I was of the idea that lock meant close the tomb.

It is working as it should.

```
 ~ $ > tomb -v
  Tomb 2.9.0 - a strong and gentle undertaker for your secrets

   Copyright (C) 2007-2021 Dyne.org Foundation, License GNU GPL v3+
   This is free software: you are free to change and redistribute it
   For the latest sourcecode go to <http://dyne.org/software/tomb>

   This source code is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   When in need please refer to <http://dyne.org/support>.

  System utils:

  zsh 5.7.1 (x86_64-debian-linux-gnu)
  Sudo version 1.8.27
  cryptsetup 2.1.0
  pinentry-curses (pinentry) 1.1.0
  findmnt from util-linux 2.33.1
  gpg (GnuPG) 2.2.12 - key forging algorithms (GnuPG symmetric ciphers):
  IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256

  Optional utils:

  /usr/bin/gettext
  dcfldd not found
  /usr/bin/shred
  steghide not found
  /sbin/resize2fs
  tomb-kdb-pbkdf2 not found
  /usr/bin/qrencode
  swish-e not found
  unoconv not found
  /usr/bin/lsof
```
