### ISSUE TITLE
support doas

### ISSUE THREAD

**Issue by marcusatiliusregulus** [dyne/Tomb#410]
please support alternatives to `sudo`, such as `doas`. you could provide a flag `--sudo <users-choice>` like `yay` does...

**Comment by jaromil** [comment]
@marcusatiliusregulus I wholeheartedly agree with this request, ready to accept PR proposals, else I will try to find the time to make one myself, that may take a month or two

**Comment by heat-wave** [comment]
Added **doas** support in #412

**Comment by marcusatiliusregulus** [comment]
thanks
