### ISSUE TITLE
how to install qt-tray?

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [dyne/Tomb#413]
Once you build tomb-qt-tray, where do you install it (`/usr/bin`)? Do you also need the stuff in `extras/qt-tray/i18n` and  `extras/qt-tray/pixmap`  folders? If yes, where to put them?

**Comment by Narrat** [comment]
It is advised to not place files into locations which are under control by the package manager of your distro.
So you wouldn't place this in `/usr/bin` but in `/usr/local/bin` (or in a special place in your home directory and extend `$PATH` with it).
Regarding the secondary files.. they're in general optional.
i18n files go to `/usr/share/i18n` (should be `/usr/local/share/i18n` if manually installed; dunno if there is a equivalent in `$HOME`, but I suppose there is)
Pixmap files go to `/usr/share/pixmaps` (should be `/usr/local/share/pixmaps` if manually installed; dunno if there is a equivalent in `$HOME`, but I suppose there is).

But that depends on the fact, that the paths aren't hardcoded in qt-tray, which I didn't check.
