### ISSUE TITLE
Okay to Force for RAM Disks?

### ISSUE THREAD

**Issue by creese** [dyne/Tomb#414]
My swap is all in RAM. Is there any reason not to force, and is this a bug in the check?

I'm running Fedora 34.

**Comment by Narrat** [comment]
Is it easily checkable if a swap device is virtual or a real block device (or file)? That could be the foremost reason why there is no differentation between the various methods to create swap.
In that regard I'm currently not sure how Tomb handles encrypted swap partitions/files, which are also more secure than plain swap.
About the security. Well, from the top of my head I don't know a reason against forcing, so feel free to do so.

**Comment by jaromil** [comment]
Not sure why you swap RAM inside RAM 😅 joking, just curious about your setup. Anyway just force is fine, detection would be overhead, conscious use is to be preferred.

**Comment by Narrat** [comment]
Compression and vastly faster access times where the reasons for me when I used it on my R500 before I upgraded the Laptop to 8GB RAM and SSD.
Came by default with 2GB plus normal HDD and once the browser was open plus some additional stuff there was heavy swapping involved. Noticeable in performance. After Swap in RAM and active compression the usability was vastly better.

**Comment by creese** [comment]
@jaromil Fedora 34 [does not use swap partitions](https://fedoraproject.org/wiki/Changes/SwapOnZRAM#Overview_of_the_Feature) by default.
