### ISSUE TITLE
DM-UUID for device tomb.XXX.loop4 was truncated.

### ISSUE THREAD

**Issue by bidetaggle** [dyne/Tomb#423]
Hello, I wanted to open a tomb and I get:

```
...
tomb . Password OK.
DM-UUID for device tomb.XXX.loop4 was truncated.
device-mapper: reload ioctl on tomb.XXX.loop4 (254:0) failed: Invalid argument
tomb [E] Failure mounting the encrypted file.
```

Does it mean there is a problem with the LUKS headers?

**Comment by jaromil** [comment]
@bidetaggle please post tomb -v output...

also is XXX literal or what is in place? what is the length?

**Comment by bidetaggle** [comment]
Hi @jaromil , actually it was due to a kernel update without reboot. I made it work, sorry to have bothered.

I'd like to use tomb on a live usb (and this issue prevents me to do so), do you know a distro where it's included by default? I found dynebolic but the file download zone says it was modified 9 years ago.
