### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by marhu98** [dyne/Tomb#424]
When I run: in the docker image I get the following error:
`tomb lock secret.tomb -k secret.tomb.key`

```
tomb [W] File is not yet a tomb: secret.tomb
sha256sum: invalid option -- 'z'
Try 'sha256sum --help' for more information.
losetup: cannot find an unused loop device: No such device
basename: missing operand
Try 'basename --help' for more information.
tomb  .  Valid tomb file found: secret.tomb
tomb  .  Commanded to lock tomb secret.tomb
losetup: cannot find an unused loop device: No such device
tomb [W] Loop mount of volumes is not possible on this machine, this error
tomb [W] often occurs on VPS and kernels that don't provide the loop module.
tomb [W] It is impossible to use Tomb on this machine under these conditions.
tomb [E] Operation aborted.
```
I believe I followed the instructions correctly. What am I doing wrong?

**Comment by jaromil** [comment]
What docker image are you using?

The reason for the error is an outdated `sha256sum` program.

**Comment by marhu98** [comment]
I'm using the docker image given in the README.md: https://github.com/dyne/Tomb/tree/master/extras/docker.

Updating openssl does nothing, I solved it by changing ubuntu:bionic to ubuntu:fossa

**Comment by jaromil** [comment]
@marhu98 ✌️🏾 well done! I updated it to dyne/devuan:beowulf which works as well. I believe mileage may vary on win10 platforms as loopback mount seems a problem at least with WLS, you are welcome to share any other experience in your journey
