### ISSUE TITLE
reimplementation of cat fails to work for some inputs

### ISSUE THREAD

**Issue by eliotb** [dyne/tomb#426]
I'm running tomb from git head, on ubuntu 20.04, bash shell, with zsh also installed.

The output of `tomb ps` is incorrect.  It seems that the invocations of `_cat` in `list_processes` return nothing.
puid and pcmd are empty and powner is list of all accounts.

If I replace _cat with system cat  by defining `_cat() { cat ${1} }`  then `tomb ps` works correctly.

I don't know zsh, so not sure why this is happening.  Something to do with mapfile accessing a proc entry? - I don't really know.

**Comment by jaromil** [comment]
thanks BTW, I simply started using cat
