### ISSUE TITLE
A minor error prompt for hostname

### ISSUE THREAD

**Issue by Inesgor** [dyne/Tomb#428]
Hi. 
I keep getting an error/warning, like while opening a tomb.
`mount_tomb:156: command not found: hostname`
However I am still able to open & close the tomb volumes properly (i guess).
I think this is a minor issue, but please let me know if there is a fix.

Thank you.

**Comment by jaromil** [comment]
tomb is trying to execute hostname rather than reading the file in etc. this is a rather old school redundant behavior, could just change to detect file and write .host if found

**Comment by Inesgor** [comment]
This prompt occurred because i didn't have `inetutils` installed. So this is fixed.
