### ISSUE TITLE
Too much noise about sudo in console output

### ISSUE THREAD

**Issue by jmstacey** [dyne/Tomb#431]
Tomb (master) is too noisy/chatty about `sudo` out of the box. It is polluting the console output with redundant and unhelpful messages that sudo is being used, and the noise makes it difficult to see relevant and useful information.

I suggest Lines 116-117 be removed, or wrapped in a new non-default --verbose option, or as part of existing -D debug option.

https://github.com/dyne/Tomb/blob/84ef4bef4b329420ff45f50eb40221b8163e3101/tomb#L115-L117

**Comment by jaromil** [comment]
you are right
