### ISSUE TITLE
swap presence should stop blocking operations 

### ISSUE THREAD

**Issue by jaromil** [dyne/tomb#44]
it is way too extreme to stop operations for the presence of swap; this behavior wasn't even discussed.

OTOH the swap vulnerability counts.

tomb runs as root so it could check for presence of a swap and execute swapoff/on -a 

until this is implemented we cannot block the operation, but in case print out a warning.

**Comment by eloyesp** [comment]
> The swapoff -a solution is problematic, as we've discussed: swapoff -a may lead to system hanging for minutes (reading data from swap) or even crashing completely (if the ram isn't enough).

Could you ask about doing that instead of just suggesting that? That will add some usability (and prevent some typing) while making sure that the user know what's happening.

```
tomb [W] This poses a security risk.
tomb [W] You can deactivate all swap partitions using the command:
tomb [W]  swapoff -a
tomb [W] Should I do that for you (it may take a while) (Y/n):
```

Also a setting for always doing that would be awesome.

**Comment by hellekin** [comment]
On 06/09/2016 03:13 AM, Eloy Espinaco wrote:
> 
> Could you ask about doing that instead of just suggesting that?
>

I don't think it's a good idea:

1. swapping off safely is not a simple task
2. swapping off is a task that doesn't belong to tomb's scope
3. making users lazy and uninformed is not the goal of the program

If you have good reason to use unencrypted swap (hint: you probably
don't) it's not Tomb's call, but yours.  If you want security, you
shouldn't use clear swap, and tutorials abound to encrypt your swap,
that take less time and effort than coding a proper solution for all cases.

**Comment by eloyesp** [comment]
Ok, didn't know about that.

On the other hand if the recommended approach is encrypting the swap, the
hint should say something about it (besides teaching `swapoff -a`), that
should be possible as is just changing the error message. in
https://github.com/dyne/Tomb/blob/master/tomb#L332

**Comment by jaromil** [comment]
Tomb has no interactivity by design choice, so that it can be used in shell scripts. In the few cases of interactivity the use of `--force` is suggested to confirm, as also in this case. We may eliminate the `swapoff -a` recommendation and just leave the possibility to `--force`.

**Comment by eloyesp** [comment]
Why not add a note with a link about encrypting the swap (like
https://gitlab.com/cryptsetup/cryptsetup/wikis/FrequentlyAskedQuestions).
(For the record, encrypting the swap is not that easy.)

---  Eloy

2016-06-09 10:27 GMT-03:00 D.J.R. <notifications@github.com>:
