### ISSUE TITLE
Support .wav file in bury/exhume mode which `steghide` already support

### ISSUE THREAD

**Issue by amalgame21** [dyne/Tomb#459]
`steghide` support image (jpeg) and audio (wav).
Are there any concern not to implement the support of .wav file?

**Comment by jaromil** [comment]
@amalgame21 the main concern I had was that is less common to have uncompressed audio on a device compared to jpg images...

**Comment by amalgame21** [comment]
But there is a software out there (`stegdetech`) claims that can be used to detect stenography in image... (I didn't try that though).
I still keep flac CD rip music on my devices (can be decompressed to .wav files > steghide > back to flac), but maybe you are right, most of the people just use spotify nowadays...

**Comment by amalgame21** [comment]
Just looked into the source code, it is  too complicated for me to modified...
I think it would be better to use .wav file separately with steghide.

I just discover this tool few days ago, it is a very good tool! good job!
