### ISSUE TITLE
age support for key encryption

### ISSUE THREAD

**Issue by jaromil** [dyne/Tomb#460]
Age is a very comfortable tool compared to GPG
https://github.com/FiloSottile/age

it also integrates with ssh keys for asymmetric crypto and supports yubi keys

it is ideal to add support for age encryption of keys in tomb

**Comment by jaromil** [comment]
Abandoning this idea since it would make tombs incompatible.

**Comment by lunics** [comment]
Could you explain or give the link to understand how the tomb key works ? Is it totally impossible to replace it by an age key, or add an option the use age at the end ?
I really appreciate the couple of Yubikey + Age.

**Comment by Narrat** [comment]
Not only `age` is gaining traction or favours.
The news on [Sequoia](https://sequoia-pgp.org/) seems to suggest its adoption is only a matter of time. https://lwn.net/Articles/1003243/
Although at the moment it would be easier to adopt `sequoia` as it seems to provide a gpg compatibility layer.

But maybe it is still worth to look into supporting different tools.

That being said. Didn't look into the topic myself yet and up to now I scuttled around the code which deals with the key creation and encryption :D Therefore I would also be interested to hear the rationale.
