### ISSUE TITLE
Translations help - perl or shell script?

### ISSUE THREAD

**Issue by nerun** [dyne/Tomb#482]
I have started a translation to Brazilian Portuguese (pt_BR), it's a WIP, but 44% complete.

I noticed that `extras/translations/tomb.pot` was outdated so I ran the perl script `generate_translatable_strings.pl` (just because Makefile uses it) to create a new version and then created a `pt_BR.po` file.

I have tried shell script `generate_translatable_strings.sh` but it has some issues and duplicated strings. Poedit can remove duplications anyway.

Since i have started with the old tomb.pot i ran `msgmerge --update pt_BR.po tomb.pot`

My question is: to create a new translation, i must use perl or shell script?

There are differences in output, for example:

perl output:
```
Listing processes running inside tomb '::1 tombname::'...
```
shell output:
```
Listing processes running inside tomb '::1 tombname::'..." "$1
```

There are worst problems than that.

**Comment by jaromil** [comment]
Of the two choices above, the perl output looks like the correct one. I am not sure what other problems are there.

However, we used weblate for tomb, I just created a BR_pt one there
https://hosted.weblate.org/projects/tomb/tomb/pt_BR/

**Comment by jaromil** [comment]
[tomb-tomb-pt_BR.zip](https://github.com/dyne/Tomb/files/11884097/tomb-tomb-pt_BR.zip)

here is the .PO file in case you don't like to use weblate
