### ISSUE TITLE
Forging a key fails at password prompt

### ISSUE THREAD

**Issue by lyndhurst** [dyne/Tomb#488]
I found similar issues, but dating back a while and marked as fixed.
I am using manjaro kde, tomb 2.10.0. Forging a key with or without `sudo` ends with

```
tomb (*) Choose the password of your key: test.tomb.key
tomb  .  (You can also change it later using 'tomb passwd'.)
pinentry-gtk-2: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
tomb [W] Empty password
tomb [E] User aborted.
```

More about my setup:

```
  System utils:

  zsh 5.9 (x86_64-pc-linux-gnu)
  Sudo version 1.9.14p3
  cryptsetup 2.6.1 flags: UDEV BLKID KEYRING KERNEL_CAPI 
  pinentry-curses (pinentry) 1.2.1
  findmnt from util-linux 2.39.1
  gpg (GnuPG) 2.2.41 - key forging algorithms (GnuPG symmetric ciphers):
  IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256

  Optional utils:

  /usr/bin/gettext
  dcfldd not found
  /usr/bin/shred
  steghide not found
  /usr/bin/resize2fs
  tomb-kdb-pbkdf2 not found
  /usr/bin/argon2
  /usr/bin/qrencode
  swish-e not found
  unoconv not found
  /usr/bin/lsof
```

**Comment by jaromil** [comment]
Is there a problem in Manjaro due to the deprecation of gtk2? I doubt we can't solve this.

**Comment by Narrat** [comment]
Dunno in what way Manjaro still follows Arch.
But on Arch `gtk2` is just an optional dep of `pinentry`. So the easy fix would be installing gtk2. Or adjust what pinentry is the default (like `pinentry-gnome3` or `pinentry-curses`)

**Comment by lyndhurst** [comment]
Changing the default pinentry is not an option for me, but you are right, installing gtk2 solves the issue.
Thanks.
