### ISSUE TITLE
Warnings not being printed

### ISSUE THREAD

**Issue by baryluk** [dyne/Tomb#502]
```
$ tomb lock secret.tomb -k secret.tomb.key
tomb  .  File is not yet a tomb: secret.tomb
tomb  .  Valid tomb file found: secret.tomb
tomb  .  Commanded to lock tomb secret.tomb
losetup: secret.tomb: failed to set up loop device: Permission denied
tomb [E] Loopback mount failed: secret.tomb on /dev/loop1
```

This is not due to sudo, but actually because root has no permission to the location this file is on (sshfs). As you can see, it is able to run losetup (using sudo), but losetup fails. This can be solved on my side, by doing sshfs mount with `-o allow_other`.

Anyway, diagnostic is a bit weird a missing. The thing is if I `strace -f -s 1000 -v -e execve ...`,  I see some extra diagnostics:

```
tomb [W] Loop mount of volumes is not possible on this machine, this error
tomb [W] often occurs on VPS and kernels that don't provide the loop module.
tomb [W] It is impossible to use Tomb on this machine under these conditions.
```

Not sure why it does not show normally.

tomb 2.10, from Debian testing

**Comment by jaromil** [comment]
Hi! I think this is due to the default debug level which excludes warnings. Worth cheking if they aren't many and if generally useful then enable them to be shown by default.

**Comment by jaromil** [comment]
tests currently show warnings by default so this seems fixed.
