### ISSUE TITLE
Add option to format tomb with a real-time compressed filesystem (btrfs + zstd)

### ISSUE THREAD

**Issue by jaromil** [dyne/tomb#537]
Using the flag `compress-force=zstd:1` it seems that btrfs obtains very good results, see these benchmarks:
https://new.reddit.com/user/FictionWorm____/comments/sxw8ky/benchmark_btrfs_51107612generic_zstdforcelog/

This may come very useful in case of maildir folders and other kinds of highly compressed data like plain-text and low entropy files.

It would be handy to have an option to specify in an easy way (one flag only) to format a tomb using btrfs and zstd=1

**Comment by Narrat** [comment]
Sounds like a case for `--filesystem` and as a name `btrfscompressed`/`btrfsc`?
Makes me wonder if there should be a `--no-filesystem` option which allows to manually format the tomb. Helps to avoid adding all wishes that may come up (`zfs`, `bcachefs`, `xfs` or *BSD related ones) or deny the inclusion of those without an easy way to still allow customization.

**Comment by jaromil** [comment]
After covering btrfs with tests and running some more custom benchmarks on my end, I realized that `btrfsmixed` is not working very well, especially its resize fails (see currently commented test in master).

Your `--filesystem=custom` or `--filesystem=none` idea is cool, but we need to rely on kernel-level implementation of autodetection on mount then. I am not sure if this is warranted or like in case of btrfs we need to do it by hand.

**Comment by jaromil** [comment]
Closing and spawning a no-format issue wishlist
