### ISSUE TITLE
Please use grep -E instead of egrep

### ISSUE THREAD

**Issue by bugtracker2019** [dyne/tomb#553]
Hello tomb-devs,

I'm using the latest version of grep (3.11) and everytime a tomb is openend, the following annoying warning message shows up:
`egrep: warning: egrep is obsolescent; using grep -E`

See [grep documentation](https://www.gnu.org/software/grep/manual/grep.html#Usage) under _4.17 What happened to egrep and fgrep?_.

Please change the tomb source code line 389 accordingly to:
`| grep -Eq '^crypt$'`

**Comment by Narrat** [comment]
Thanks for reporting.
I was wondering why I didn't get the warning, as 3.11 is around since a year already. But no wonder: I don't have a swap.
